Repository kubernetes-sigs/jobset, pull requests merged in 2023-04, with the labels that each got.

#2 Add JobSet types
  api/v1alpha1/jobset_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/batch.x-k8s.io_jobsets.yaml
Labels: tide/merge-method-squash, cncf-cla: yes, size/XXL, lgtm, approved

#5 Initial controller implementation
  Makefile
  api/v1alpha1/jobset_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/batch.x-k8s.io_jobsets.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/controllers/suite_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, size/XL, lgtm, approved

#8 Add integration tests
  Makefile
  go.mod
  go.sum
  pkg/controllers/jobset_controller.go
  pkg/util/testing/core.go
  pkg/util/testing/wrappers.go
  test/integration/jobset_controller_test.go
  test/integration/suite_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, size/XL, lgtm, approved

#14 Use contextual logging
  pkg/controllers/jobset_controller.go
Labels: tide/merge-method-squash, cncf-cla: yes, size/M, lgtm, approved

#16 add dependabot
  .github/dependabot.yml
Labels: cncf-cla: yes, lgtm, approved, size/S

#15 Add support for creating multiple instances of the same job template
  api/v1alpha1/jobset_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/batch.x-k8s.io_jobsets.yaml
  pkg/controllers/jobset_controller.go
  pkg/util/testing/wrappers.go
  test/integration/jobset_controller_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved

#19 Validation and defaulting using kubebuilder markers
  api/v1alpha1/jobset_types.go
  config/crd/bases/batch.x-k8s.io_jobsets.yaml
  pkg/controllers/jobset_controller.go
  pkg/util/testing/core.go
  pkg/util/testing/wrappers.go
  test/integration/jobset_controller_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved

#24 add events when conditions are set
  config/rbac/role.yaml
  main.go
  pkg/controllers/jobset_controller.go
  test/integration/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#23 Add support for failure policy of target=Any and restartPolicy=RecreateAll
  api/v1alpha1/jobset_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/batch.x-k8s.io_jobsets.yaml
  pkg/controllers/jobset_controller.go
  pkg/util/testing/wrappers.go
  test/integration/jobset_controller_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, size/XL, lgtm, approved

#25 Update Dockerfile and update readme with installation instructions
  Dockerfile
  README.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#29 Fix make test command so it only runs unit tests and not integration
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#28 Add more failure policy integration tests and refactor into table driven format
  pkg/controllers/jobset_controller.go
  test/integration/jobset_controller_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, size/XL, lgtm, approved

#36 Add support for 1:1 job per topology assignment
  Makefile
  api/v1alpha1/jobset_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/batch.x-k8s.io_jobsets.yaml
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/util/testing/wrappers.go
  test/integration/jobset_controller_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved

#37 Add additional labels/annotations, and add unit tests for constructJobsFromTemplate
  api/v1alpha1/jobset_types.go
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/util/testing/wrappers.go
  test/integration/jobset_controller_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, size/XL, lgtm, approved

#42 One headless service per replicatedJob when pod DNS hostnames is enabled
  api/v1alpha1/jobset_types.go
  config/crd/bases/batch.x-k8s.io_jobsets.yaml
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  test/integration/jobset_controller_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#44 Add cloudbuild.yaml and update Makefile
  Makefile
  README.md
  cloudbuild.yaml
  config/rbac/role.yaml
  pkg/controllers/jobset_controller.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved

#45 Use jobset and replicated job names as selectors for headless svc
  api/v1alpha1/jobset_types.go
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  test/integration/jobset_controller_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved

#49 Validate job spec is immutable
  api/v1alpha1/jobset_types.go
  config/crd/bases/batch.x-k8s.io_jobsets.yaml
  test/integration/jobset_controller_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved

#50 Update image-build cmd and installation instructions to reduce build time
  Makefile
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#51 Set up defaulting webhook
  Makefile
  PROJECT
  README.md
  api/v1alpha1/jobset_webhook.go
  api/v1alpha1/jobset_webhook_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/manager/kustomization.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  main.go
  test/integration/controller/jobset_controller_test.go
  test/integration/controller/suite_test.go
  test/integration/webhook/jobset_webhook_test.go
  test/integration/webhook/suite_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, size/XL, lgtm, approved

#57 Added initial structure for docs
  README.md
  cloudbuild.yaml
  docs/README.md
  docs/concepts/README.md
  docs/setup/README.md
  docs/setup/install.md
  docs/tasks/README.md
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved

#54 feat: use internal cert
  Dockerfile
  config/default/kustomization.yaml
  config/internalcert/kustomization.yaml
  config/internalcert/secret.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  main.go
  pkg/controllers/jobset_controller.go
  pkg/util/cert/cert.go
  test/integration/controller/suite_test.go
  test/integration/webhook/suite_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, ok-to-test, lgtm, size/L, approved

#68 Update RBAC roles
  config/rbac/role.yaml
Labels: tide/merge-method-squash, cncf-cla: yes, size/M, lgtm, approved

#66 Renamed api group from batch.x-k8s.io to jobset.x-k8s.io
  PROJECT
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/jobset_webhook.go
  config/crd/bases/jobset.x-k8s.io_jobsets.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_jobsets.yaml
  config/crd/patches/webhook_in_jobsets.yaml
  config/rbac/jobset_editor_role.yaml
  config/rbac/jobset_viewer_role.yaml
  config/samples/batch_v1alpha1_jobset.yaml
  config/webhook/manifests.yaml
Labels: tide/merge-method-squash, cncf-cla: yes, size/XXL, lgtm, approved

#65 API cleanup
  api/v1alpha1/jobset_types.go
  api/v1alpha1/jobset_webhook.go
  api/v1alpha1/jobset_webhook_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/batch.x-k8s.io_jobsets.yaml
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/util/testing/wrappers.go
  test/integration/controller/jobset_controller_test.go
  test/integration/webhook/jobset_webhook_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved

#70 Point the deployment scripts to the dev image
  config/crd/bases/jobset.x-k8s.io_jobsets.yaml
  config/manager/kustomization.yaml
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, approved, size/S

#72 Migrate remaining references to the old api group
  config/rbac/role.yaml
  pkg/controllers/jobset_controller.go
Labels: tide/merge-method-squash, cncf-cla: yes, size/M, lgtm, approved

#73 Enable dns hostnames by default if job template uses indexed completion mode
  api/v1alpha1/jobset_webhook.go
  api/v1alpha1/jobset_webhook_test.go
  test/integration/webhook/jobset_webhook_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, size/M, lgtm, approved

#56 Add e2e test
  Makefile
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  hack/e2e-test.sh
  test/e2e/config/image_pull_policy.yaml
  test/e2e/config/kustomization.yaml
  test/e2e/e2e_test.go
  test/e2e/suite_test.go
  test/integration/controller/jobset_controller_test.go
  test/util/util.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved

#74 Update e2e make rule with step to download kustomize binary
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#76 Default pod restart policy to OnFailure
  api/v1alpha1/jobset_webhook.go
  api/v1alpha1/jobset_webhook_test.go
  test/e2e/suite_test.go
  test/integration/webhook/jobset_webhook_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved

#79 Fix the json tag for replicatedJobs field
  api/v1alpha1/jobset_types.go
  config/crd/bases/jobset.x-k8s.io_jobsets.yaml
Labels: kind/bug, tide/merge-method-squash, cncf-cla: yes, lgtm, size/XS, approved

#81 Fix json tags
  api/v1alpha1/jobset_types.go
  config/crd/bases/batch.x-k8s.io_jobsets.yaml
  config/crd/bases/jobset.x-k8s.io_jobsets.yaml
Labels: tide/merge-method-squash, cncf-cla: yes, size/XXL, lgtm, approved

#80 Add pytorch example
  examples/pytorch/resnet.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#64 Adding concepts page to the docs
  docs/concepts/README.md
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved

#83 Bump controller-gen version to fix null conversion issue
  Makefile
  config/crd/bases/jobset.x-k8s.io_jobsets.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  hack/e2e-test.sh
Labels: cncf-cla: yes, lgtm, approved, size/S

#84 Increase log level to 2 by default
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, approved, size/S

#63 remove CEL validation, validate inside the webhook
  api/v1alpha1/jobset_types.go
  api/v1alpha1/jobset_webhook.go
  test/integration/controller/jobset_controller_test.go
  test/integration/webhook/jobset_webhook_test.go
Labels: cncf-cla: yes, ok-to-test, size/M, lgtm, approved

#88 make network optional and add optional tags to namespace selector
  api/v1alpha1/jobset_types.go
  config/crd/bases/jobset.x-k8s.io_jobsets.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#89 require templates in replicatejobs
  api/v1alpha1/jobset_types.go
  config/crd/bases/jobset.x-k8s.io_jobsets.yaml
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/XS, approved

#86 adding a simple parallel sleep and fix validation with pytorch
  examples/simple/paralleljobs.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#20 feat: add suspend to jobset api
  api/v1alpha1/jobset_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/jobset.x-k8s.io_jobsets.yaml
  config/samples/batch_v1alpha1_jobset.yaml
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/util/testing/wrappers.go
  test/integration/controller/jobset_controller_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, ok-to-test, size/XL, lgtm, approved

#91 Added a link to the concepts page
  README.md
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/XS, approved

#92 Fix install command in docs
  docs/setup/install.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#94 Update pytorch example so training logs are visible
  examples/pytorch/resnet.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#95 Add PyTorch MNIST example
  examples/pytorch/mnist.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved
