Repository kubernetes-sigs/jobset, pull requests merged in 2023-12, with the labels that each got.

#343 add flags for qps and burst instead of hardcoding them
  main.go
Labels: cncf-cla: yes, ok-to-test, lgtm, size/XS, approved

#333 allow for podman to be used for running tests
  hack/python-sdk/test-sdk.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#342 Update pod reconciler to handle race conditions in exclusive placement
  pkg/controllers/pod_controller.go
  pkg/util/placement/placement.go
  pkg/webhooks/pod_admission_webhook.go
  pkg/webhooks/pod_mutating_webhook.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved

#348 [release-0.3 branch] Update with installation docs with v0.3.0
  docs/setup/install.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#349 Update main branch installation docs for release v0.3.0
  docs/setup/install.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#352 use kind export logs
  hack/e2e-test.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#250 add suspend to replicated job status
  api/jobset/v1alpha2/jobset_types.go
  api/jobset/v1alpha2/openapi_generated.go
  client-go/applyconfiguration/jobset/v1alpha2/replicatedjobstatus.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  hack/python-sdk/swagger.json
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  sdk/python/docs/JobsetV1alpha2ReplicatedJobStatus.md
  sdk/python/jobset/models/jobset_v1alpha2_replicated_job_status.py
  sdk/python/test/test_jobset_v1alpha2_job_set.py
  sdk/python/test/test_jobset_v1alpha2_job_set_list.py
  sdk/python/test/test_jobset_v1alpha2_job_set_status.py
  sdk/python/test/test_jobset_v1alpha2_replicated_job_status.py
  test/integration/controller/jobset_controller_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#354 Update the installation docs to mention the CPU nodes minimum necessary CPU/memory resources
  docs/setup/install.md
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/XS, approved

#358 Use jobset-system instead of kind-system for jobset
  hack/e2e-test.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#244 A KEP for StartupPolicy
  keps/104-StartupPolicy/README.md
  keps/104-StartupPolicy/kep.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved

#362 Add patches for Kustomize to add objectSelectors to pod webhook configurations
  config/components/webhook/kustomization.yaml
  config/components/webhook/patches/mutating-patch.yaml
  config/components/webhook/patches/validating-patch.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#365 Automated cherry pick of #362: add webhook patches
  config/components/webhook/kustomization.yaml
  config/components/webhook/patches/mutating-patch.yaml
  config/components/webhook/patches/validating-patch.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#368 Update installation docs for v0.3.1 [main]
  docs/setup/install.md
Labels: cncf-cla: yes, lgtm, approved, size/S
