Repository kubernetes-sigs/jobset, pull requests merged in 2023-05, with the labels that each got.

#98 Move exclusiveness to annotation
  api/v1alpha1/jobset_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/jobset.x-k8s.io_jobsets.yaml
  docs/concepts/README.md
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/util/testing/wrappers.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved

#96 Add failure policy with max restarts example
  examples/simple/max-restarts.yaml
Labels: tide/merge-method-squash, cncf-cla: yes, size/M, lgtm, approved

#99 Allow prometheus to gather metrics published by controller-runtime
  Makefile
  config/components/certmanager/certificate.yaml
  config/components/certmanager/kustomization.yaml
  config/components/certmanager/kustomizeconfig.yaml
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  config/components/crd/kustomization.yaml
  config/components/crd/kustomizeconfig.yaml
  config/components/crd/patches/cainjection_in_jobsets.yaml
  config/components/crd/patches/webhook_in_jobsets.yaml
  config/components/internalcert/kustomization.yaml
  config/components/internalcert/secret.yaml
  config/components/manager/kustomization.yaml
  config/components/manager/manager.yaml
  config/components/prometheus/kustomization.yaml
  config/components/prometheus/monitor.yaml
  config/components/prometheus/role.yaml
  config/components/rbac/auth_proxy_client_clusterrole.yaml
  config/components/rbac/auth_proxy_role.yaml
  config/components/rbac/auth_proxy_role_binding.yaml
  config/components/rbac/auth_proxy_service.yaml
  config/components/rbac/jobset_editor_role.yaml
  config/components/rbac/jobset_viewer_role.yaml
  config/components/rbac/kustomization.yaml
  config/components/rbac/leader_election_role.yaml
  config/components/rbac/leader_election_role_binding.yaml
  config/components/rbac/role.yaml
  config/components/rbac/role_binding.yaml
  config/components/rbac/service_account.yaml
  config/components/webhook/kustomization.yaml
  config/components/webhook/kustomizeconfig.yaml
  config/components/webhook/manifests.yaml
  config/components/webhook/service.yaml
  config/default/kustomization.yaml
  config/prometheus/kustomization.yaml
  docs/setup/install.md
  hack/e2e-test.sh
  test/integration/controller/suite_test.go
  test/integration/webhook/suite_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved

#102 Add make artifacts command to makefile
  Makefile
Labels: cncf-cla: yes, lgtm, approved, size/S

#106 Update docs with installation steps for a released version
  docs/setup/install.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#107 update docs with instructions about using certmanager
  docs/setup/install.md
Labels: tide/merge-method-squash, cncf-cla: yes, ok-to-test, lgtm, approved, size/S

#108 Update installation docs
  docs/setup/install.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#110 Add jobset name and replicatedJob name as annotations
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#111 Automated cherry pick of #110: update annotations
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#112 Add cherry pick script to hack folder
  hack/cherry_pick_pull.sh
Labels: cncf-cla: yes, lgtm, size/L, approved

#113 Fix simple example
  examples/simple/paralleljobs.yaml
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, approved, size/S

#109 Refactor suspend/resume logic in Reconcile()
  pkg/controllers/jobset_controller.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#118 Propagate errors to trigger reconciliation when they happen
  pkg/controllers/jobset_controller.go
Labels: tide/merge-method-squash, cncf-cla: yes, size/M, lgtm, approved

#119 Fix default success policy
  pkg/controllers/jobset_controller.go
  test/e2e/e2e_test.go
  test/integration/controller/jobset_controller_test.go
  test/util/util.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved

#121 Automated cherry pick of #118: Propagation errors to trigger reconciliation when they happen
  pkg/controllers/jobset_controller.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, approved, size/S

#122 Automated cherry pick of #119: fix default success policy
  pkg/controllers/jobset_controller.go
  test/e2e/e2e_test.go
  test/integration/controller/jobset_controller_test.go
  test/util/util.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#129 update go to 1.20
  Dockerfile
  go.mod
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/XS, approved

#126 Update docs for v0.1.3
  docs/setup/install.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#125 Pass a context from controller to the IndexerFunc
  main.go
  pkg/controllers/jobset_controller.go
  test/integration/controller/suite_test.go
  test/integration/webhook/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#115 remove namespace deletion as it is not recommended from kubebuilder
  test/integration/controller/jobset_controller_test.go
  test/integration/webhook/jobset_webhook_test.go
  test/util/util.go
Labels: tide/merge-method-squash, cncf-cla: yes, size/M, lgtm, approved

#123 Limit the number of goroutines used when deleting jobs
  pkg/controllers/jobset_controller.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#139 Relax validation on enableDNSHostnames
  api/v1alpha1/jobset_webhook.go
  test/integration/controller/jobset_controller_test.go
  test/integration/webhook/jobset_webhook_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#124 Add Success Policy to JobSet API
  Dockerfile
  api/v1alpha1/jobset_types.go
  api/v1alpha1/jobset_webhook.go
  api/v1alpha1/jobset_webhook_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  pkg/controllers/jobset_controller.go
  pkg/util/collections/collections.go
  pkg/util/testing/wrappers.go
  test/integration/controller/jobset_controller_test.go
  test/integration/webhook/jobset_webhook_test.go
  test/util/util.go
Labels: tide/merge-method-squash, cncf-cla: yes, size/XL, lgtm, approved

#147 Add unit tests for collections package
  pkg/util/collections/collections_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#153 Bump timeouts to reduce flakiness
  test/e2e/e2e_test.go
  test/e2e/suite_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#143 Set node affinity during unsuspend
  api/v1alpha1/jobset_types.go
  api/v1alpha1/jobset_webhook.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  pkg/controllers/jobset_controller.go
  test/integration/controller/jobset_controller_test.go
  test/integration/webhook/jobset_webhook_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, ok-to-test, lgtm, size/L, approved

#155 Adding junit reports to test and test-integration
  Makefile
  hack/e2e-test.sh
Labels: tide/merge-method-squash, cncf-cla: yes, ok-to-test, lgtm, approved, size/S

#159 Suspend field should be mutable
  api/v1alpha1/jobset_webhook.go
  test/integration/webhook/jobset_webhook_test.go
Labels: kind/bug, tide/merge-method-squash, cncf-cla: yes, ok-to-test, size/M, lgtm, approved

#160 fixed resetting start time bug
  pkg/controllers/jobset_controller.go
Labels: kind/bug, tide/merge-method-squash, cncf-cla: yes, ok-to-test, lgtm, size/XS, approved

#144 Ready replicates jobs status
  api/v1alpha1/jobset_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  go.mod
  go.sum
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/util/testing/wrappers.go
  test/integration/controller/jobset_controller_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, ok-to-test, lgtm, size/L, approved

#167 Fix bug with setting node selectors when resuming suspended jobset
  pkg/controllers/jobset_controller.go
  test/integration/controller/jobset_controller_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, approved, size/S

#165 Add `Completed` and `Restarts` printcolumns to JobSet
  api/v1alpha1/jobset_types.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
Labels: cncf-cla: yes, ok-to-test, lgtm, approved, size/S

#168 Delete active jobs for finished JobSets
  pkg/controllers/jobset_controller.go
  test/integration/controller/jobset_controller_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, size/M, lgtm, approved
