Repository kubernetes-sigs/jobset, pull requests merged in 2023-07, with the labels that each got.

#221 Automatically move generated client-go files to repo root
  hack/update-codegen.sh
Labels: cncf-cla: yes, lgtm, approved, size/S

#220 use int32 rather than int
  api/jobset/v1alpha2/jobset_types.go
  client-go/applyconfiguration/jobset/v1alpha2/failurepolicy.go
  client-go/applyconfiguration/jobset/v1alpha2/jobsetstatus.go
  client-go/applyconfiguration/jobset/v1alpha2/replicatedjob.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  pkg/controllers/jobset_controller.go
  pkg/util/testing/wrappers.go
  sdk/python/requirements.txt
  test/e2e/e2e_test.go
  test/integration/controller/jobset_controller_test.go
  test/util/util.go
Labels: tide/merge-method-squash, cncf-cla: yes, size/M, lgtm, approved

#225 Use get_namespaced_custom_object for getting jobset
  sdk/python/examples/create_jobset.py
Labels: cncf-cla: yes, lgtm, size/XS, approved

#223 Add pyproject.toml and cleanup sdk installation
  hack/python-sdk/gen-sdk.sh
  sdk/python/pyproject.toml
  sdk/python/pyvenv.cfg
  sdk/python/requirements.txt
  sdk/python/setup.py
Labels: tide/merge-method-squash, cncf-cla: yes, size/M, lgtm, approved

#226 Automated cherry pick of #223: use pyproject.toml
  hack/python-sdk/gen-sdk.sh
  sdk/python/pyproject.toml
  sdk/python/pyvenv.cfg
  sdk/python/requirements.txt
  sdk/python/setup.py
Labels: cncf-cla: yes, size/M, lgtm, approved

#227 Automated cherry pick of #225: use get_namespaced_custom_object for getting jobset
  sdk/python/examples/create_jobset.py
Labels: cncf-cla: yes, lgtm, size/XS, approved

#228 Remove generate target from build, run and test targets
  Makefile
Labels: cncf-cla: yes, ok-to-test, lgtm, approved, size/S
