Repository kubernetes-sigs/jobset, pull requests merged in 2023-06, with the labels that each got.

#172 Reset StartTime before updating the jobs NodeSelector
  api/v1alpha1/jobset_types.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  pkg/controllers/jobset_controller.go
  test/integration/controller/jobset_controller_test.go
  test/util/util.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved

#173 Add Go client
  Makefile
  PROJECT
  api/jobset/v1alpha1/doc.go
  api/jobset/v1alpha1/groupversion_info.go
  api/jobset/v1alpha1/jobset_types.go
  api/jobset/v1alpha1/jobset_webhook.go
  api/jobset/v1alpha1/jobset_webhook_test.go
  api/jobset/v1alpha1/zz_generated.deepcopy.go
  client-go/clientset/versioned/clientset.go
  client-go/clientset/versioned/fake/clientset_generated.go
  client-go/clientset/versioned/fake/doc.go
  client-go/clientset/versioned/fake/register.go
  client-go/clientset/versioned/scheme/doc.go
  client-go/clientset/versioned/scheme/register.go
  client-go/clientset/versioned/typed/jobset/v1alpha1/doc.go
  client-go/clientset/versioned/typed/jobset/v1alpha1/fake/doc.go
  client-go/clientset/versioned/typed/jobset/v1alpha1/fake/fake_jobset.go
  client-go/clientset/versioned/typed/jobset/v1alpha1/fake/fake_jobset_client.go
  client-go/clientset/versioned/typed/jobset/v1alpha1/generated_expansion.go
  client-go/clientset/versioned/typed/jobset/v1alpha1/jobset.go
  client-go/clientset/versioned/typed/jobset/v1alpha1/jobset_client.go
  client-go/informers/externalversions/factory.go
  client-go/informers/externalversions/generic.go
  client-go/informers/externalversions/internalinterfaces/factory_interfaces.go
  client-go/informers/externalversions/jobset/interface.go
  client-go/informers/externalversions/jobset/v1alpha1/interface.go
  client-go/informers/externalversions/jobset/v1alpha1/jobset.go
  client-go/listers/jobset/v1alpha1/expansion_generated.go
  client-go/listers/jobset/v1alpha1/jobset.go
  go.mod
  go.sum
  hack/update-codegen.sh
  main.go
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/util/testing/wrappers.go
  test/e2e/e2e_test.go
  test/e2e/suite_test.go
  test/integration/controller/jobset_controller_test.go
  test/integration/controller/suite_test.go
  test/integration/webhook/jobset_webhook_test.go
  test/integration/webhook/suite_test.go
  test/util/util.go
Labels: tide/merge-method-squash, cncf-cla: yes, size/XXL, lgtm, approved

#182 Added failed jobs in replicated job statuses
  api/jobset/v1alpha1/jobset_types.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
Labels: kind/feature, cncf-cla: yes, ok-to-test, size/M, lgtm, approved

#183 update jobset api to v1alpha2
  PROJECT
  api/jobset/v1alpha2/doc.go
  api/jobset/v1alpha2/groupversion_info.go
  api/jobset/v1alpha2/jobset_types.go
  api/jobset/v1alpha2/jobset_webhook.go
  api/jobset/v1alpha2/jobset_webhook_test.go
  api/jobset/v1alpha2/zz_generated.deepcopy.go
  client-go/clientset/versioned/clientset.go
  client-go/clientset/versioned/fake/clientset_generated.go
  client-go/clientset/versioned/fake/register.go
  client-go/clientset/versioned/scheme/register.go
  client-go/clientset/versioned/typed/jobset/v1alpha2/doc.go
  client-go/clientset/versioned/typed/jobset/v1alpha2/fake/doc.go
  client-go/clientset/versioned/typed/jobset/v1alpha2/fake/fake_jobset.go
  client-go/clientset/versioned/typed/jobset/v1alpha2/fake/fake_jobset_client.go
  client-go/clientset/versioned/typed/jobset/v1alpha2/generated_expansion.go
  client-go/clientset/versioned/typed/jobset/v1alpha2/jobset.go
  client-go/clientset/versioned/typed/jobset/v1alpha2/jobset_client.go
  client-go/informers/externalversions/generic.go
  client-go/informers/externalversions/jobset/interface.go
  client-go/informers/externalversions/jobset/v1alpha2/interface.go
  client-go/informers/externalversions/jobset/v1alpha2/jobset.go
  client-go/listers/jobset/v1alpha2/expansion_generated.go
  client-go/listers/jobset/v1alpha2/jobset.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  config/components/webhook/manifests.yaml
  config/samples/batch_v1alpha2_jobset.yaml
  docs/concepts/README.md
  docs/setup/install.md
  examples/pytorch/mnist.yaml
  examples/pytorch/resnet.yaml
  examples/simple/max-restarts.yaml
  examples/simple/paralleljobs.yaml
  hack/update-codegen.sh
  main.go
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/util/testing/wrappers.go
  test/e2e/e2e_test.go
  test/e2e/suite_test.go
  test/integration/controller/jobset_controller_test.go
  test/integration/controller/suite_test.go
  test/integration/webhook/jobset_webhook_test.go
  test/integration/webhook/suite_test.go
  test/util/util.go
Labels: cncf-cla: yes, ok-to-test, lgtm, size/L, approved

#184 validation sum of replicas and parallelism inside int32 range
  api/jobset/v1alpha2/jobset_webhook.go
  api/jobset/v1alpha2/jobset_webhook_test.go
  go.mod
Labels: kind/bug, tide/merge-method-squash, cncf-cla: yes, ok-to-test, size/M, lgtm, approved

#171 add support for Network.Subdomain
  api/jobset/v1alpha2/jobset_types.go
  api/jobset/v1alpha2/jobset_webhook.go
  api/jobset/v1alpha2/jobset_webhook_test.go
  api/jobset/v1alpha2/zz_generated.deepcopy.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/util/testing/wrappers.go
  test/e2e/e2e_test.go
  test/integration/controller/jobset_controller_test.go
  test/integration/webhook/jobset_webhook_test.go
Labels: cncf-cla: yes, ok-to-test, lgtm, size/L, approved

#188 Added active status of jobset for integration with kueue
  api/jobset/v1alpha2/jobset_types.go
  client-go/applyconfiguration/jobset/v1alpha2/replicatedjobstatus.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/util/testing/wrappers.go
Labels: kind/feature, tide/merge-method-squash, cncf-cla: yes, ok-to-test, size/M, lgtm, approved

#181 Recalculate and update ReplicatedJobsStatuses on last reconciler iteration when all jobs are succeeded
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  test/integration/controller/jobset_controller_test.go
Labels: cncf-cla: yes, ok-to-test, size/M, lgtm, approved

#201 update gen-sdk.sh to fallback to openjdk-17
  hack/python-sdk/gen-sdk.sh
  hack/python-sdk/post_gen.py
  hack/python-sdk/test-sdk.sh
Labels: cncf-cla: yes, ok-to-test, lgtm, approved, size/S

#194 update subdomain tests
  pkg/controllers/jobset_controller_test.go
  pkg/util/testing/wrappers.go
  test/e2e/e2e_test.go
  test/integration/controller/jobset_controller_test.go
Labels: cncf-cla: yes, ok-to-test, lgtm, approved, size/S

#206 Fix openapi spec generation
  Makefile
  api/jobset/v1alpha2/openapi_generated.go
  hack/python-sdk/swagger.json
  sdk/python/docs/JobsetV1alpha2JobSetSpec.md
  sdk/python/docs/JobsetV1alpha2Network.md
  sdk/python/docs/JobsetV1alpha2ReplicatedJob.md
  sdk/python/docs/JobsetV1alpha2ReplicatedJobStatus.md
  sdk/python/jobset/models/jobset_v1alpha2_job_set_spec.py
  sdk/python/jobset/models/jobset_v1alpha2_network.py
  sdk/python/jobset/models/jobset_v1alpha2_replicated_job.py
  sdk/python/jobset/models/jobset_v1alpha2_replicated_job_status.py
  sdk/python/test/test_jobset_v1alpha2_job_set.py
  sdk/python/test/test_jobset_v1alpha2_job_set_list.py
  sdk/python/test/test_jobset_v1alpha2_job_set_spec.py
  sdk/python/test/test_jobset_v1alpha2_job_set_status.py
  sdk/python/test/test_jobset_v1alpha2_network.py
  sdk/python/test/test_jobset_v1alpha2_replicated_job.py
  sdk/python/test/test_jobset_v1alpha2_replicated_job_status.py
Labels: cncf-cla: yes, lgtm, size/L, approved

#213 Make kind cluster creation block until control plane ready
  hack/e2e-test.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#209 Update examples to use JobSet name as subdomain
  examples/pytorch/mnist.yaml
  examples/pytorch/resnet.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#214 add kind logs
  hack/e2e-test.sh
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, approved, size/S

#203 add example and update setup.py to semi functional
  hack/python-sdk/test-sdk.sh
  sdk/python/Dockerfile
  sdk/python/examples/README.md
  sdk/python/examples/create_jobset.py
  sdk/python/requirements.txt
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved

#211 Add job hash key (sha1 hash of namespaced job name) as label and annotation for setting exclusive affinities
  api/jobset/v1alpha2/jobset_types.go
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, size/M, lgtm, approved

#215 eventually updates
  test/integration/controller/jobset_controller_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, size/M, lgtm, approved

#216 Update installation docs for v0.2.0
  docs/setup/install.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#217 Update installation docs for v0.2.0 (main branch)
  docs/setup/install.md
Labels: cncf-cla: yes, lgtm, approved, size/S
