Repository kubernetes-sigs/jobset, pull requests merged in 2023-11, with the labels that each got.

#328 Parallelize job creation
  pkg/controllers/jobset_controller.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#327 Self-nominate kannon92 for a reviewer for jobset.
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#329 Migrate to use kube_codegen.sh to generate client
  Makefile
  api/jobset/v1alpha2/types.go
  hack/update-codegen.sh
Labels: cncf-cla: yes, ok-to-test, size/M, lgtm, approved

#309 Add pod webhook + reconciler for new "leader pod" exclusive job placement strategy
  Dockerfile
  api/jobset/v1alpha2/jobset_webhook.go
  config/components/manager/manager.yaml
  config/components/rbac/role.yaml
  config/components/webhook/manifests.yaml
  examples/simple/exclusive-placement.yaml
  main.go
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/controllers/pod_controller.go
  pkg/util/names/names.go
  pkg/util/shared/shared.go
  pkg/webhooks/pod_admission_webhook.go
  pkg/webhooks/pod_admission_webhook_test.go
  pkg/webhooks/pod_mutating_webhook.go
  test/e2e/suite_test.go
  test/integration/controller/suite_test.go
  test/integration/webhook/suite_test.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#340 Rename shared pkg to placement
  api/jobset/v1alpha2/jobset_webhook.go
  pkg/controllers/jobset_controller.go
  pkg/util/placement/placement.go
  pkg/webhooks/pod_admission_webhook.go
Labels: cncf-cla: yes, lgtm, approved, size/S
