Repository kubernetes-sigs/jobset, pull requests merged in 2023-08, with the labels that each got.

#242 add kep template
  keps/NNNN-template/README.md
  keps/NNNN-template/kep.yaml
  keps/README.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#245 cover some unit test gaps in jobset_webhook.go
  api/jobset/v1alpha2/jobset_webhook_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#243 add an example for success policy
  examples/simple/driver-worker-success-policy.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#248 add patch rbac for events
  config/components/rbac/role.yaml
  pkg/controllers/jobset_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#252 boiler plate code for kep templating
  Makefile
  hack/.notableofcontents
  hack/update-toc.sh
  hack/verify-toc.sh
Labels: cncf-cla: yes, lgtm, size/L, approved

#255 pointer to ptr conversion
  go.mod
  go.sum
  pkg/controllers/jobset_controller.go
  pkg/util/testing/wrappers.go
  test/integration/controller/jobset_controller_test.go
  test/integration/webhook/jobset_webhook_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#254 add golangci and fix some minor items
  .golangci.yaml
  Makefile
  api/jobset/v1alpha2/jobset_webhook.go
  api/jobset/v1alpha2/jobset_webhook_test.go
  test/e2e/e2e_test.go
  test/integration/controller/jobset_controller_test.go
  test/integration/webhook/jobset_webhook_test.go
  test/util/util.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#256 Add source to pytorch mnist example
  examples/pytorch/cnn-mnist/Dockerfile
  examples/pytorch/cnn-mnist/mnist.py
  examples/pytorch/cnn-mnist/mnist.yaml
  examples/pytorch/resnet-cifar10/resnet.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved

#259 Automated cherry pick of #248: add patch rbac for events
  config/components/rbac/role.yaml
  pkg/controllers/jobset_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#264 Update installation docs for v0.2.1
  docs/setup/install.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#265 Fail fast if we cannot build indexes
  main.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#266 Automated cherry pick of #265: fail fast if we cannot build indexes
  main.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#268 Add update/patch rbac verbs for resource jobs/status
  config/components/rbac/role.yaml
  pkg/controllers/jobset_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#271 Automated cherry pick of #268: add update/patch rbac verbs for resource jobs/status
  config/components/rbac/role.yaml
  pkg/controllers/jobset_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved
