Repository kubernetes-sigs/jobset, pull requests merged in 2023-09, with the labels that each got.

#287 Remove incompatible shuffle option from cuda args
  examples/pytorch/cnn-mnist/mnist.py
Labels: cncf-cla: yes, lgtm, size/XS, approved

#293 Update docs to use latest release
  docs/setup/install.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#278 Add validation enforcing that network subdomain adheres to RFC 1035
  api/jobset/v1alpha2/jobset_webhook.go
  api/jobset/v1alpha2/jobset_webhook_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#253 add a tensorflow example and update task documentation
  docs/tasks/README.md
  examples/simple/max-restarts.yaml
  examples/simple/paralleljobs.yaml
  examples/simple/success-policy.yaml
  examples/tensorflow/mnist.yaml
Labels: tide/merge-method-squash, cncf-cla: yes, size/M, lgtm, approved

#284 Validate the generated job names will be dns 1035 compliant
  api/jobset/v1alpha2/jobset_webhook.go
  api/jobset/v1alpha2/jobset_webhook_test.go
  pkg/controllers/jobset_controller.go
  pkg/util/names/names.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#303 Add troubleshooting docs
  README.md
  docs/faq/README.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#306 upgrade to k8s 1.28
  Makefile
  client-go/informers/externalversions/factory.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  go.mod
  go.sum
  hack/update-codegen.sh
  main.go
  test/integration/webhook/suite_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#307 Update troubleshooting docs
  docs/faq/README.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#311 Add node selector strategy for exclusive job placement per topology
  api/jobset/v1alpha2/jobset_types.go
  hack/label_nodes/label_nodes.py
  hack/label_nodes/requirements.txt
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/util/testing/wrappers.go
Labels: cncf-cla: yes, lgtm, size/L, approved
