Repository kubernetes-sigs/jobset, pull requests merged in 2024-08, with the labels that each got.

#634 chore: add github issue, pr template
  .github/ISSUE_TEMPLATE/bug_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf-cla: yes, size/M, lgtm, kind/cleanup, approved

#636 fix error output
  pkg/webhooks/pod_admission_webhook.go
  pkg/webhooks/pod_mutating_webhook.go
Labels: kind/bug, cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#641 Bump k8s dependencies to 1.30 dependencies and modify update-codegen.sh to be compatible with new code-generator
  client-go/applyconfiguration/jobset/v1alpha2/jobsetstatus.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  go.mod
  go.sum
  hack/update-codegen.sh
Labels: cncf-cla: yes, size/XL, lgtm, approved

#645 Fix bug in replicatedJobByName
  pkg/webhooks/jobset_webhook.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#644 Allow to update JobSets on suspend
  pkg/webhooks/jobset_webhook.go
  pkg/webhooks/jobset_webhook_test.go
  test/e2e/e2e_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#646 Refactor jobset webhook
  pkg/webhooks/jobset_webhook.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved

#643 add the unparam linter to golangci and fix those issues flagged
  .golangci.yaml
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, kind/cleanup, approved, size/S

#642 drop job-name from labels as it is not used
  api/jobset/v1alpha2/jobset_types.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#650 Add new job-id annotation to assign globally unique job index to each job
  api/jobset/v1alpha2/jobset_types.go
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved

#651 Automated cherry pick of #644: Allow to update jobSets on suspend
  pkg/webhooks/jobset_webhook.go
  pkg/webhooks/jobset_webhook_test.go
  test/e2e/e2e_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#654 update to k8s 0.30.4
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, lgtm, kind/cleanup, approved

#657 Fix typo in docs
  site/content/en/docs/tasks/_index.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#656 Update readme for v0.6.0 in release branch
  README.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#658 Readme update for 0.6.0 [main]
  README.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#660 Update docsite installation for v0.6.0
  site/config.toml
Labels: cncf-cla: yes, lgtm, approved

#661 Update readme with new failure policy details for v0.6.0
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#667 fix: delete active jobs right away when job finishes even when TTLSecondsAfterFinished is set
  pkg/controllers/jobset_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved
