Repository kubernetes-sigs/jobset, pull requests merged in 2024-06, with the labels that each got.

#589 update makefile kind version to v1.30.0
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#590 Propagate Job pod template updates to suspended jobs when resuming
  pkg/controllers/jobset_controller.go
  pkg/util/collections/collections.go
  pkg/util/collections/collections_test.go
  test/integration/controller/jobset_controller_test.go
Labels: tide/merge-method-merge, cncf-cla: yes, lgtm, size/L, approved

#591 Automated cherry pick of #590: propagate job pod template updates to suspended jobs when
  pkg/controllers/jobset_controller.go
  pkg/util/collections/collections.go
  pkg/util/collections/collections_test.go
  test/integration/controller/jobset_controller_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#593 docs: update to v0.5.2
  README.md
  site/config.toml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#595 fix: fix log to avoid panic
  pkg/controllers/failure_policy.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#598 avoid log panic
  pkg/controllers/pod_controller.go
  pkg/webhooks/pod_admission_webhook.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#596 Add omitempty to annotation of OnJobFailureReasons.
  api/jobset/v1alpha2/jobset_types.go
  api/jobset/v1alpha2/openapi_generated.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  hack/python-sdk/swagger.json
  sdk/python/docs/JobsetV1alpha2FailurePolicyRule.md
  sdk/python/jobset/models/jobset_v1alpha2_failure_policy_rule.py
  sdk/python/test/test_jobset_v1alpha2_failure_policy_rule.py
Labels: tide/merge-method-squash, cncf-cla: yes, ok-to-test, lgtm, approved, size/S

#602 update readme docs e2e test version to v1.30
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#604 Update _index.md `MASTER_ADDR`
  site/content/en/docs/concepts/_index.md
Labels: cncf-cla: yes, ok-to-test, lgtm, size/XS, approved

#606 Add client-go example
  examples/client-go/README.md
  examples/client-go/go.mod
  examples/client-go/go.sum
  examples/client-go/main.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved

#608 Wait for the webhook service to be listening before advertising the Jobset replica as ready.
  main.go
  test/e2e/suite_test.go
Labels: kind/feature, cncf-cla: yes, size/M, lgtm, approved

#550 docs: add simple example for network field
  README.md
  RELEASE.md
  examples/simple/jobset-with-network.yaml
  site/content/en/docs/troubleshooting/_index.md
  site/static/examples/simple/jobset-with-network.yaml
Labels: tide/merge-method-squash, cncf-cla: yes, ok-to-test, lgtm, size/L, approved

#594 feat: add terminalState to jobset status
  api/jobset/v1alpha2/jobset_types.go
  api/jobset/v1alpha2/openapi_generated.go
  client-go/applyconfiguration/jobset/v1alpha2/jobsetstatus.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  hack/python-sdk/swagger.json
  pkg/controllers/failure_policy.go
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/util/testing/wrappers.go
  sdk/python/docs/JobsetV1alpha2JobSetStatus.md
  sdk/python/jobset/models/jobset_v1alpha2_job_set_status.py
  sdk/python/test/test_jobset_v1alpha2_job_set.py
  sdk/python/test/test_jobset_v1alpha2_job_set_list.py
  sdk/python/test/test_jobset_v1alpha2_job_set_status.py
  test/util/util.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved
