Repository kubernetes-sigs/jobset, pull requests merged in 2024-12, with the labels that each got.

#718 fix wget failure to resolve relative paths
  hack/python-sdk/gen-sdk.sh
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#719 Allow for one to install jobset in a different namespace
  main.go
  pkg/util/cert/cert.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/S

#722 Remove kube-rbac-proxy
  config/components/rbac/auth_proxy_client_binding.yaml
  config/components/rbac/auth_proxy_client_clusterrole.yaml
  config/components/rbac/auth_proxy_role.yaml
  config/components/rbac/auth_proxy_role_binding.yaml
  config/components/rbac/auth_proxy_service.yaml
  config/components/rbac/kustomization.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/default/manager_metrics_service.yaml
  go.mod
  go.sum
  main.go
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/L, approved

#732 Update documents to point to v0.7.2
  README.md
  site/config.toml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#727 fix docker warnings
  Dockerfile
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved

#728 upgrade python dependencies for sdk
  sdk/python/Dockerfile
  sdk/python/pyproject.toml
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#680 KEP-672: Serial Job Execution with DependsOn API
  keps/672-serial-job-execution/README.md
  keps/672-serial-job-execution/jobset-serial-execution.png
  keps/672-serial-job-execution/kep.yaml
Labels: kind/feature, tide/merge-method-squash, cncf-cla: yes, ok-to-test, size/XL, lgtm, approved

#735 update golang net to 0.33 to satisfy security alerts
  go.mod
  go.sum
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, approved
