Repository kubernetes-sigs/jobset, pull requests merged in 2024-09, with the labels that each got.

#670 Bump kubernetes dependencies to v0.31.x.
  .golangci.yaml
  Makefile
  client-go/applyconfiguration/jobset/v1alpha2/coordinator.go
  client-go/applyconfiguration/jobset/v1alpha2/failurepolicy.go
  client-go/applyconfiguration/jobset/v1alpha2/failurepolicyrule.go
  client-go/applyconfiguration/jobset/v1alpha2/jobset.go
  client-go/applyconfiguration/jobset/v1alpha2/jobsetspec.go
  client-go/applyconfiguration/jobset/v1alpha2/jobsetstatus.go
  client-go/applyconfiguration/jobset/v1alpha2/network.go
  client-go/applyconfiguration/jobset/v1alpha2/replicatedjob.go
  client-go/applyconfiguration/jobset/v1alpha2/replicatedjobstatus.go
  client-go/applyconfiguration/jobset/v1alpha2/startuppolicy.go
  client-go/applyconfiguration/jobset/v1alpha2/successpolicy.go
  client-go/applyconfiguration/utils.go
  client-go/clientset/versioned/fake/clientset_generated.go
  client-go/clientset/versioned/typed/jobset/v1alpha2/fake/fake_jobset.go
  client-go/clientset/versioned/typed/jobset/v1alpha2/jobset.go
  client-go/informers/externalversions/factory.go
  client-go/listers/jobset/v1alpha2/jobset.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  config/components/rbac/role.yaml
  go.mod
  go.sum
  pkg/features/features.go
  pkg/webhooks/jobset_webhook.go
  pkg/webhooks/jobset_webhook_test.go
  site/content/en/docs/reference/jobset.v1alpha2.md
Labels: cncf-cla: yes, size/XL, lgtm, kind/cleanup, approved

#673 Add test-python-sdk on Makefile test.
  Makefile
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#609 feat: add component config
  PROJECT
  api/config/v1alpha1/configuration_types.go
  api/config/v1alpha1/defaults.go
  api/config/v1alpha1/defaults_test.go
  api/config/v1alpha1/groupversion_info.go
  api/config/v1alpha1/zz_generated.deepcopy.go
  api/config/v1alpha1/zz_generated.defaults.go
  config/components/crd/bases/jobset.x-k8s.io_configurations.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_configurations.yaml
  config/crd/patches/webhook_in_configurations.yaml
  config/rbac/configuration_editor_role.yaml
  config/rbac/configuration_viewer_role.yaml
  config/samples/jobset_v1alpha1_configuration.yaml
  main.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/validation.go
  pkg/config/validation_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, ok-to-test, size/XXL, lgtm, approved, release-0.7

#677 Add global-job-replicas label/annotation
  api/jobset/v1alpha2/jobset_types.go
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
Labels: kind/feature, tide/merge-method-squash, cncf-cla: yes, ok-to-test, size/M, lgtm, approved

#601 Add examples for three existing failure policy actions.
  examples/failure-policy/failjobset-action.yaml
  examples/failure-policy/host-maintenance-event-model.yaml
  examples/failure-policy/onjobfailurereasons-present-podfailurepolicy.yaml
  examples/failure-policy/onjobfailurereasons-present.yaml
  examples/failure-policy/restartjobset-action.yaml
  examples/failure-policy/restartjobsetandignoremaxrestarts-action.yaml
Labels: tide/merge-method-squash, cncf-cla: yes, ok-to-test, lgtm, size/L, approved

#630 chore: use symbolic link instead of directory
  README.md
  examples
  examples/pytorch/cnn-mnist/Dockerfile
  examples/pytorch/cnn-mnist/mnist.py
  examples/pytorch/cnn-mnist/mnist.yaml
  examples/pytorch/resnet-cifar10/resnet.yaml
  examples/simple/exclusive-placement.yaml
  examples/simple/jobset-with-network.yaml
  examples/simple/max-restarts.yaml
  examples/simple/paralleljobs.yaml
  examples/simple/success-policy.yaml
  examples/simple/ttl-after-finished.yaml
  examples/tensorflow/mnist.yaml
  site/static/examples/argo-workflow/rbac.yaml
  site/static/examples/argo-workflow/workflow.yaml
  site/static/examples/client-go/README.md
  site/static/examples/client-go/go.mod
  site/static/examples/client-go/go.sum
  site/static/examples/client-go/main.go
  site/static/examples/failure-policy/failjobset-action.yaml
  site/static/examples/failure-policy/host-maintenance-event-model.yaml
  site/static/examples/failure-policy/onjobfailurereasons-present-podfailurepolicy.yaml
  site/static/examples/failure-policy/onjobfailurereasons-present.yaml
  site/static/examples/failure-policy/restartjobset-action.yaml
  site/static/examples/failure-policy/restartjobsetandignoremaxrestarts-action.yaml
  site/static/examples/prometheus-operator/README.md
  site/static/examples/prometheus-operator/prometheus.png
  site/static/examples/prometheus-operator/prometheus.yaml
  site/static/examples/simple/coordinator.yaml
  site/static/examples/startup-policy/startup-driver-ready.yaml
Labels: tide/merge-method-squash, cncf-cla: yes, size/XL, lgtm, kind/cleanup, approved
