Repository kubernetes-sigs/jobset, pull requests merged in 2024-03, with the labels that each got.

#442 Add descriptions to ReplicatedJobStatus fields
  api/jobset/v1alpha2/jobset_types.go
  api/jobset/v1alpha2/openapi_generated.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  hack/python-sdk/swagger.json
  sdk/python/docs/JobsetV1alpha2ReplicatedJobStatus.md
  sdk/python/jobset/models/jobset_v1alpha2_replicated_job_status.py
Labels: cncf-cla: yes, lgtm, size/L, approved

#446 Add JobSet diagram and other doc updates
  README.md
  docs/concepts/README.md
  docs/troubleshooting/README.md
  site/static/images/jobset_diagram.png
Labels: cncf-cla: yes, size/M, lgtm, approved

#450 Update installation version to latest release in public docs
  site/content/en/docs/installation/_index.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#454 add concept image
  site/content/en/docs/concepts/_index.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#453 Update tasks documentation
  site/content/en/docs/faq/_index.md
  site/content/en/docs/tasks/_index.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#448 Emit Job creation failed event
  pkg/controllers/jobset_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#455 Remove Jobset Docs from root
  docs/README.md
  docs/concepts/README.md
  docs/reference/README.md
  docs/reference/metrics.md
  docs/setup/README.md
  docs/setup/install.md
  docs/tasks/README.md
  docs/troubleshooting/README.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#456 Fix 404 error when clicking on driver-worker-success-policy.yaml
  site/content/en/docs/tasks/_index.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#457 Rename FAQ to troubleshooting on docsite
  site/content/en/docs/troubleshooting/_index.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#452 Add features overview to README
  README.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#470 Update Makefile rules to use more specific paths
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#472 Fix typo in readme
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#468 Add jobset roadmap to README
  README.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#471 update golang to 1.22
  Dockerfile
  go.mod
Labels: cncf-cla: yes, lgtm, size/XS, approved

#480 Lower default resource request for controller manager but keep high limit
  config/components/manager/manager.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#477 Include first failed job name in event emitted when JobSet fails, as well as the JobSet failure condition
  Dockerfile
  pkg/constants/constants.go
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/controllers/pod_controller.go
  pkg/controllers/success_policy.go
  test/integration/controller/jobset_controller_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#486 Update README.md to correct concepts link
  README.md
Labels: cncf-cla: yes, ok-to-test, lgtm, size/XS, approved

#484 Code cleanup and refactoring
  pkg/constants/constants.go
  pkg/controllers/jobset_controller.go
  pkg/controllers/startup_policy.go
  pkg/controllers/startup_policy_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#483 Move headless service creation outside of createJobs
  pkg/controllers/jobset_controller.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#488 Remove Duplicate Import
  pkg/controllers/pod_controller.go
Labels: cncf-cla: yes, ok-to-test, lgtm, size/XS, approved

#487 Introduce `managedBy` field and Remove `managed-by` label
  api/jobset/v1alpha2/jobset_types.go
  api/jobset/v1alpha2/jobset_webhook.go
  api/jobset/v1alpha2/jobset_webhook_test.go
  api/jobset/v1alpha2/openapi_generated.go
  api/jobset/v1alpha2/zz_generated.deepcopy.go
  client-go/applyconfiguration/jobset/v1alpha2/jobsetspec.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  hack/python-sdk/swagger.json
  pkg/controllers/jobset_controller.go
  pkg/util/testing/wrappers.go
  sdk/python/docs/JobsetV1alpha2JobSetSpec.md
  sdk/python/jobset/models/jobset_v1alpha2_job_set_spec.py
  sdk/python/test/test_jobset_v1alpha2_job_set.py
  sdk/python/test/test_jobset_v1alpha2_job_set_list.py
  sdk/python/test/test_jobset_v1alpha2_job_set_spec.py
  test/integration/controller/jobset_controller_test.go
  test/integration/webhook/jobset_webhook_test.go
Labels: cncf-cla: yes, ok-to-test, lgtm, size/L, approved

#489 fix some typo error
  README.md
  api/jobset/v1alpha2/jobset_types.go
  pkg/controllers/pod_controller.go
  pkg/webhooks/pod_admission_webhook.go
Labels: cncf-cla: yes, ok-to-test, lgtm, approved, size/S
