Repository kubernetes-sigs/jobset, pull requests merged in 2024-07, with the labels that each got.

#610 Integration test improvement: rename "update" to "step"
  test/integration/controller/jobset_controller_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#612 docs: add argo workflow example for jobset
  examples/argo-workflow/rbac.yaml
  examples/argo-workflow/workflow.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved

#611 docs: add JobSet API reference
  Makefile
  hack/genref/config.yaml
  hack/genref/markdown/members.tpl
  hack/genref/markdown/pkg.tpl
  hack/genref/markdown/type.tpl
  site/content/en/docs/reference/jobset.v1alpha2.md
Labels: cncf-cla: yes, size/XL, lgtm, approved

#615 docs: fix typo, Github -> GitHub
  site/content/en/_index.html
Labels: cncf-cla: yes, ok-to-test, lgtm, size/XS, approved

#618 Add Coordinator field to JobSet spec
  api/jobset/v1alpha2/jobset_types.go
  api/jobset/v1alpha2/openapi_generated.go
  api/jobset/v1alpha2/zz_generated.deepcopy.go
  client-go/applyconfiguration/jobset/v1alpha2/coordinator.go
  client-go/applyconfiguration/jobset/v1alpha2/jobsetspec.go
  client-go/applyconfiguration/utils.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  hack/python-sdk/swagger.json
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/util/testing/wrappers.go
  sdk/python/README.md
  sdk/python/docs/JobsetV1alpha2Coordinator.md
  sdk/python/docs/JobsetV1alpha2JobSetSpec.md
  sdk/python/jobset/__init__.py
  sdk/python/jobset/models/__init__.py
  sdk/python/jobset/models/jobset_v1alpha2_coordinator.py
  sdk/python/jobset/models/jobset_v1alpha2_job_set_spec.py
  sdk/python/test/test_jobset_v1alpha2_coordinator.py
  sdk/python/test/test_jobset_v1alpha2_job_set.py
  sdk/python/test/test_jobset_v1alpha2_job_set_list.py
  sdk/python/test/test_jobset_v1alpha2_job_set_spec.py
  test/integration/controller/jobset_controller_test.go
Labels: cncf-cla: yes, size/XL, lgtm, approved

#627 Validation for Coordinator field
  pkg/webhooks/jobset_webhook.go
  pkg/webhooks/jobset_webhook_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#628 Add example for coordinator
  examples/simple/coordinator.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#629 docs: add prometheus-operator example for jobset
  examples/prometheus-operator/README.md
  examples/prometheus-operator/prometheus.png
  examples/prometheus-operator/prometheus.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved

#633 docs: update metrics info for site
  site/content/en/docs/reference/metrics.md
Labels: cncf-cla: yes, lgtm, approved, size/S
