Repository kubernetes-sigs/jobset, pull requests merged in 2024-04, with the labels that each got.

#460 Move JobSet webhook into same webhooks package as pod webhook
  Makefile
  api/jobset/v1alpha2/zz_generated.deepcopy.go
  go.mod
  go.sum
  main.go
  pkg/webhooks/jobset_webhook.go
  pkg/webhooks/jobset_webhook_test.go
  pkg/webhooks/pod_mutating_webhook.go
  test/integration/webhook/suite_test.go
Labels: cncf-cla: yes, size/XL, lgtm, approved

#464 add unit test for jobset webhook updates
  pkg/webhooks/jobset_webhook_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#443 feat: add support for ttl cleanup for finished jobsets
  api/jobset/v1alpha2/jobset_types.go
  api/jobset/v1alpha2/openapi_generated.go
  api/jobset/v1alpha2/zz_generated.deepcopy.go
  client-go/applyconfiguration/jobset/v1alpha2/jobsetspec.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  examples/simple/ttl-after-finished.yaml
  hack/python-sdk/swagger.json
  pkg/controllers/jobset_controller.go
  pkg/controllers/ttl_after_finished.go
  pkg/controllers/ttl_after_finished_test.go
  pkg/util/testing/wrappers.go
  sdk/python/docs/JobsetV1alpha2JobSetSpec.md
  sdk/python/jobset/models/jobset_v1alpha2_job_set_spec.py
  sdk/python/test/test_jobset_v1alpha2_job_set.py
  sdk/python/test/test_jobset_v1alpha2_job_set_list.py
  sdk/python/test/test_jobset_v1alpha2_job_set_spec.py
  test/integration/controller/jobset_controller_test.go
  test/util/util.go
Labels: tide/merge-method-squash, cncf-cla: yes, ok-to-test, size/XL, lgtm, approved

#501 Add unit tests to jobset success policy functions
  pkg/controllers/success_policy.go
  pkg/controllers/success_policy_test.go
Labels: cncf-cla: yes, ok-to-test, lgtm, size/L, approved

#503 fix: add IsNotFoundErr when get headlessSvc
  pkg/controllers/jobset_controller.go
Labels: cncf-cla: yes, ok-to-test, lgtm, size/XS, approved

#510 Update envtest and add back crd generation when updating the api
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#494 Call Status.Update once in each reconcile attempt
  api/jobset/v1alpha2/jobset_types.go
  pkg/constants/constants.go
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/controllers/startup_policy.go
  pkg/util/testing/wrappers.go
  test/integration/controller/jobset_controller_test.go
  test/util/util.go
Labels: tide/merge-method-squash, cncf-cla: yes, size/XL, lgtm, approved

#512 Clean up outdated comments
  pkg/controllers/jobset_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#517 Update docs for 0.5.0
  README.md
  site/content/en/docs/installation/_index.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#520 Update main branch docs for v0.5.0
  README.md
  site/content/en/docs/installation/_index.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#521 doc: add ttlSecondsAfterFinished example
  site/content/en/docs/tasks/_index.md
  site/static/examples/simple/ttl-after-finished.yaml
Labels: cncf-cla: yes, ok-to-test, size/M, lgtm, approved

#511 feat: add e2e test for ttl seconds after finished in jobset
  pkg/util/testing/wrappers.go
  test/e2e/e2e_test.go
  test/util/util.go
Labels: cncf-cla: yes, ok-to-test, size/M, lgtm, approved

#505 add publish not ready headless service to jobset
  api/jobset/v1alpha2/jobset_types.go
  api/jobset/v1alpha2/openapi_generated.go
  api/jobset/v1alpha2/zz_generated.deepcopy.go
  client-go/applyconfiguration/jobset/v1alpha2/network.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  hack/python-sdk/swagger.json
  pkg/controllers/jobset_controller.go
  pkg/util/testing/wrappers.go
  pkg/webhooks/jobset_webhook.go
  pkg/webhooks/jobset_webhook_test.go
  sdk/python/docs/JobsetV1alpha2Network.md
  sdk/python/jobset/models/jobset_v1alpha2_network.py
  sdk/python/test/test_jobset_v1alpha2_job_set.py
  sdk/python/test/test_jobset_v1alpha2_job_set_list.py
  sdk/python/test/test_jobset_v1alpha2_job_set_spec.py
  sdk/python/test/test_jobset_v1alpha2_network.py
  test/e2e/e2e_test.go
  test/integration/webhook/jobset_webhook_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#522 use kube-openapi rather than code generator openapi-gen
  Makefile
  api/jobset/v1alpha2/openapi_generated.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#525 Allow passing args to ginkgo for integration tests
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#516 Refactor create jobs
  pkg/controllers/jobset_controller.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#528 Do not default the managedBy field
  pkg/webhooks/jobset_webhook.go
  pkg/webhooks/jobset_webhook_test.go
  test/integration/webhook/jobset_webhook_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#507 feat: add event recorder event
  pkg/constants/constants.go
  pkg/controllers/jobset_controller.go
Labels: cncf-cla: yes, ok-to-test, lgtm, size/XS, approved

#532 use t.Errorf instead of t.Fatalf
  pkg/controllers/ttl_after_finished_test.go
Labels: cncf-cla: yes, ok-to-test, lgtm, size/XS, approved

#527 Fix path for the error when attempting to mutate managedBy
  pkg/webhooks/jobset_webhook.go
  pkg/webhooks/jobset_webhook_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#533 [Release-0.5] Do not default the managedBy field
  pkg/webhooks/jobset_webhook.go
  pkg/webhooks/jobset_webhook_test.go
  test/integration/webhook/jobset_webhook_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#531 Fix bug when checking if a JobSet is active during tests.
  test/util/util.go
Labels: cncf-cla: yes, ok-to-test, lgtm, approved, size/S

#539 Correct typo in configurable failure policy KEP.
  keps/262-ConfigurableFailurePolicy/README.md
Labels: cncf-cla: yes, ok-to-test, lgtm, size/XS, approved

#534 Automated cherry pick of #527: Fix path for the error when mutating managedBy
  pkg/webhooks/jobset_webhook.go
  pkg/webhooks/jobset_webhook_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#544 fix: fix ci error caused by typo
  keps/262-ConfigurableFailurePolicy/README.md
Labels: cncf-cla: yes, ok-to-test, lgtm, size/XS, approved

#541 docs: fix site url not found
  site/content/en/docs/contribution guidelines/_index.md
  site/content/en/docs/troubleshooting/_index.md
Labels: cncf-cla: yes, ok-to-test, lgtm, size/XS, approved

#540 use hugo param to define variables in md language
  site/config.toml
  site/content/en/docs/installation/_index.md
Labels: cncf-cla: yes, ok-to-test, lgtm, size/XS, approved, kind/documentation

#526 add unit tests for createHeadlessSvcIfNecessary
  pkg/controllers/jobset_controller_test.go
Labels: cncf-cla: yes, ok-to-test, lgtm, size/L, approved

#490 test: add pod controller unit test
  pkg/controllers/pod_controller_test.go
  pkg/util/testing/wrappers.go
Labels: cncf-cla: yes, ok-to-test, lgtm, size/L, approved

#549 Add comment explaining why we don't unconditionally compute firstFailedJob
  pkg/controllers/jobset_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved
