Repository kubernetes-sigs/jobset, pull requests merged in 2024-10, with the labels that each got.

#687 Priority-based exclusive placement
  api/jobset/v1alpha2/jobset_types.go
  go.mod
  pkg/constants/constants.go
  pkg/webhooks/pod_mutating_webhook.go
Labels: kind/feature, tide/merge-method-squash, cncf-cla: yes, lgtm, approved, size/S

#686 Add restart strategy
  api/jobset/v1alpha2/jobset_types.go
  api/jobset/v1alpha2/openapi_generated.go
  client-go/applyconfiguration/jobset/v1alpha2/failurepolicy.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  go.mod
  hack/python-sdk/swagger.json
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  sdk/python/docs/JobsetV1alpha2FailurePolicy.md
  sdk/python/jobset/models/jobset_v1alpha2_failure_policy.py
  sdk/python/test/test_jobset_v1alpha2_failure_policy.py
  sdk/python/test/test_jobset_v1alpha2_job_set.py
  sdk/python/test/test_jobset_v1alpha2_job_set_list.py
  sdk/python/test/test_jobset_v1alpha2_job_set_spec.py
  site/content/en/docs/tasks/_index.md
  site/static/examples/simple/failure-policy.yaml
  test/integration/controller/jobset_controller_test.go
  test/integration/webhook/jobset_webhook_test.go
  test/util/util.go
Labels: kind/feature, cncf-cla: yes, ok-to-test, lgtm, size/L, approved

#691 Update docs for v0.7.0 (release branch)
  README.md
  site/config.toml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#692 Doc updates for 0.7 [main branch]
  README.md
  site/config.toml
Labels: cncf-cla: yes, lgtm, size/XS, approved
