Repository kubernetes-sigs/jobset, pull requests merged in 2024-05, with the labels that each got.

#558 docs: using kustomize for adjusting resources
  site/content/en/docs/installation/_index.md
Labels: cncf-cla: yes, ok-to-test, size/M, lgtm, approved

#562 Don't reconcile JobSets with deletion timestamp set
  pkg/controllers/jobset_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#564 Automated cherry pick of #562: don't reconcile jobsets with deletion timestamp set
  pkg/controllers/jobset_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#565 Improve the API generated docs for managedBy
  api/jobset/v1alpha2/jobset_types.go
  api/jobset/v1alpha2/openapi_generated.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  hack/python-sdk/swagger.json
  sdk/python/docs/JobsetV1alpha2JobSetSpec.md
  sdk/python/jobset/models/jobset_v1alpha2_job_set_spec.py
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/documentation

#567 chore: Upgrade e2e local image
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#557 Add support for feature gates
  go.mod
  go.sum
  main.go
  pkg/features/features.go
Labels: cncf-cla: yes, ok-to-test, size/M, lgtm, approved

#537 Implement configurable failure policy.
  api/jobset/v1alpha2/jobset_types.go
  api/jobset/v1alpha2/openapi_generated.go
  api/jobset/v1alpha2/zz_generated.deepcopy.go
  client-go/applyconfiguration/jobset/v1alpha2/failurepolicy.go
  client-go/applyconfiguration/jobset/v1alpha2/failurepolicyrule.go
  client-go/applyconfiguration/jobset/v1alpha2/jobsetstatus.go
  client-go/applyconfiguration/utils.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  hack/python-sdk/swagger.json
  pkg/constants/constants.go
  pkg/controllers/failure_policy.go
  pkg/controllers/failure_policy_test.go
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/webhooks/jobset_webhook.go
  pkg/webhooks/jobset_webhook_test.go
  sdk/python/README.md
  sdk/python/docs/JobsetV1alpha2FailurePolicy.md
  sdk/python/docs/JobsetV1alpha2FailurePolicyRule.md
  sdk/python/docs/JobsetV1alpha2JobSetStatus.md
  sdk/python/jobset/__init__.py
  sdk/python/jobset/models/__init__.py
  sdk/python/jobset/models/jobset_v1alpha2_failure_policy.py
  sdk/python/jobset/models/jobset_v1alpha2_failure_policy_rule.py
  sdk/python/jobset/models/jobset_v1alpha2_job_set_status.py
  sdk/python/test/test_jobset_v1alpha2_failure_policy.py
  sdk/python/test/test_jobset_v1alpha2_failure_policy_rule.py
  sdk/python/test/test_jobset_v1alpha2_job_set.py
  sdk/python/test/test_jobset_v1alpha2_job_set_list.py
  sdk/python/test/test_jobset_v1alpha2_job_set_spec.py
  sdk/python/test/test_jobset_v1alpha2_job_set_status.py
  test/integration/controller/jobset_controller_test.go
Labels: cncf-cla: yes, ok-to-test, size/XXL, lgtm, approved

#577 Update the JobSet version to 0.5.1 for installation
  README.md
  site/config.toml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#584 Automated cherry pick of #580: relax validation on replicated jobs
  pkg/util/testing/wrappers.go
  pkg/webhooks/jobset_webhook.go
  pkg/webhooks/jobset_webhook_test.go
  test/integration/webhook/jobset_webhook_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved
