Repository kubernetes-sigs/jobset, pull requests merged in 2024-02, with the labels that each got.

#393 Migrate from background to foreground cascading deletion policy
  pkg/controllers/jobset_controller.go
  pkg/util/collections/collections.go
  test/integration/controller/jobset_controller_test.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/L, approved

#395 Default service name in JobSet controller
  api/jobset/v1alpha2/jobset_webhook.go
  api/jobset/v1alpha2/jobset_webhook_test.go
  pkg/controllers/jobset_controller.go
  pkg/util/testing/wrappers.go
  test/integration/controller/jobset_controller_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#403 bumping controller tools to see if this fixes ci
  Makefile
  api/jobset/v1alpha2/zz_generated.deepcopy.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#400 add suspend field to printcolumn
  api/jobset/v1alpha2/jobset_types.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#402 add jobset docsite
  .gitignore
  netlify.toml
  site/.gitignore
  site/OWNERS
  site/README.md
  site/archetypes/default.md
  site/assets/icons/logo.svg
  site/assets/scss/_styles_project.scss
  site/assets/scss/_variables_project.scss
  site/config.toml
  site/content/en/_index.html
  site/content/en/docs/_index.md
  site/content/en/docs/concepts/_index.md
  site/content/en/docs/contribution guidelines/_index.md
  site/content/en/docs/faq/_index.md
  site/content/en/docs/installation/_index.md
  site/content/en/docs/reference/_index.md
  site/content/en/docs/reference/metrics.md
  site/content/en/docs/tasks/_index.md
  site/content/en/featured-background.png
  site/content/en/search.md
  site/layouts/404.html
  site/layouts/partials/feedback.html
  site/layouts/partials/footer.html
  site/layouts/partials/head.html
  site/layouts/partials/navbar-version-selector.html
  site/layouts/partials/navbar.html
  site/layouts/partials/seo_schema.html
  site/layouts/shortcodes/blocks/content-item.html
  site/layouts/shortcodes/blocks/content-section.html
  site/layouts/shortcodes/blocks/link-down.html
  site/layouts/shortcodes/blocks/sample-section.html
  site/layouts/shortcodes/blocks/tab.html
  site/layouts/shortcodes/blocks/tabs.html
  site/layouts/shortcodes/include.html
  site/layouts/shortcodes/needs-update.html
  site/layouts/shortcodes/params.html
  site/layouts/sitemap.xml
  site/package-lock.json
  site/package.json
  site/static/examples/pytorch/cnn-mnist/Dockerfile
  site/static/examples/pytorch/cnn-mnist/mnist.py
  site/static/examples/pytorch/cnn-mnist/mnist.yaml
  site/static/examples/pytorch/resnet-cifar10/resnet.yaml
  site/static/examples/simple/exclusive-placement.yaml
  site/static/examples/simple/max-restarts.yaml
  site/static/examples/simple/paralleljobs.yaml
  site/static/examples/simple/success-policy.yaml
  site/static/examples/tensorflow/mnist.yaml
  site/static/favicons/android-chrome-192x192.png
  site/static/favicons/android-chrome-512x512.png
  site/static/favicons/apple-touch-icon.png
  site/static/favicons/favicon-16x16.png
  site/static/favicons/favicon-32x32.png
  site/static/favicons/favicon.ico
  site/static/favicons/site.webmanifest
  site/static/images/logo.svg
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#381 KEP 262: Configurable Failure Policy API
  keps/262-ConfigurableFailurePolicy/README.md
  keps/262-ConfigurableFailurePolicy/kep.yaml
Labels: tide/merge-method-squash, cncf-cla: yes, size/XL, lgtm, approved

#404 Get subdomain via a func instead of defaulting it on the jobset object
  pkg/controllers/jobset_controller.go
  test/integration/controller/jobset_controller_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#246 Startup policy implementation
  api/jobset/v1alpha2/jobset_types.go
  api/jobset/v1alpha2/jobset_webhook.go
  api/jobset/v1alpha2/jobset_webhook_test.go
  api/jobset/v1alpha2/openapi_generated.go
  api/jobset/v1alpha2/zz_generated.deepcopy.go
  client-go/applyconfiguration/jobset/v1alpha2/jobsetspec.go
  client-go/applyconfiguration/jobset/v1alpha2/startuppolicy.go
  client-go/applyconfiguration/utils.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  examples/startup-policy/startup-driver-ready.yaml
  hack/python-sdk/swagger.json
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/controllers/startup_policy.go
  pkg/controllers/startup_policy_test.go
  pkg/util/testing/wrappers.go
  sdk/python/README.md
  sdk/python/docs/JobsetV1alpha2JobSetSpec.md
  sdk/python/docs/JobsetV1alpha2StartupPolicy.md
  sdk/python/docs/JobsetV1alpha2TargetReplicatedJobStartup.md
  sdk/python/jobset/__init__.py
  sdk/python/jobset/models/__init__.py
  sdk/python/jobset/models/jobset_v1alpha2_job_set_spec.py
  sdk/python/jobset/models/jobset_v1alpha2_startup_policy.py
  sdk/python/test/test_jobset_v1alpha2_job_set.py
  sdk/python/test/test_jobset_v1alpha2_job_set_list.py
  sdk/python/test/test_jobset_v1alpha2_job_set_spec.py
  sdk/python/test/test_jobset_v1alpha2_startup_policy.py
  test/integration/controller/jobset_controller_test.go
  test/util/util.go
Labels: tide/merge-method-squash, cncf-cla: yes, size/XXL, lgtm, approved

#410 Minor cleanup to ensureConditionOpts
  pkg/controllers/jobset_controller.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#409 Validate longest pod name for jobset will not exceed 63 chars
  api/jobset/v1alpha2/jobset_webhook.go
  api/jobset/v1alpha2/jobset_webhook_test.go
  pkg/util/placement/placement.go
  pkg/webhooks/pod_admission_webhook.go
  pkg/webhooks/pod_admission_webhook_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#416 Automated cherry pick of #403: bumping controller tools to see if this fixes ci
  Makefile
  api/jobset/v1alpha2/zz_generated.deepcopy.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#417 Automated cherry pick of #393: add backoff for creation
  pkg/controllers/jobset_controller.go
  pkg/util/collections/collections.go
  test/integration/controller/jobset_controller_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#418 Automated cherry pick of #395: default service name in controller
  api/jobset/v1alpha2/jobset_webhook.go
  api/jobset/v1alpha2/jobset_webhook_test.go
  pkg/controllers/jobset_controller.go
  pkg/util/testing/wrappers.go
  test/integration/controller/jobset_controller_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#419 Automated cherry pick of #404: Get subdomain via a func instead of defaulting it on the
  pkg/controllers/jobset_controller.go
  test/integration/controller/jobset_controller_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#420 Automated cherry pick of #409: validate longest pod name for jobset will not exceed 63 chars
  api/jobset/v1alpha2/jobset_webhook.go
  api/jobset/v1alpha2/jobset_webhook_test.go
  pkg/util/placement/placement.go
  pkg/webhooks/pod_admission_webhook.go
  pkg/webhooks/pod_admission_webhook_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#407 Add managed-by label support.
  api/jobset/v1alpha2/jobset_types.go
  api/jobset/v1alpha2/jobset_webhook.go
  api/jobset/v1alpha2/jobset_webhook_test.go
  pkg/controllers/jobset_controller.go
  pkg/util/testing/wrappers.go
  test/integration/controller/jobset_controller_test.go
  test/integration/webhook/jobset_webhook_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, approved

#421 Improve error messages and logging in webhooks
  api/jobset/v1alpha2/jobset_webhook.go
  api/jobset/v1alpha2/jobset_webhook_test.go
  pkg/webhooks/pod_admission_webhook.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#423 Automated cherry pick of #421: add clearer error message for pod name too long
  api/jobset/v1alpha2/jobset_webhook.go
  api/jobset/v1alpha2/jobset_webhook_test.go
  pkg/webhooks/pod_admission_webhook.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#424 Update installation docs for v0.3.2
  docs/setup/install.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#435 Add info to landing page
  site/content/en/_index.html
Labels: cncf-cla: yes, lgtm, approved, size/S

#433 Validate follower pod owned by same Job as leader pod
  pkg/controllers/pod_controller.go
  pkg/webhooks/pod_admission_webhook.go
  pkg/webhooks/pod_admission_webhook_test.go
  pkg/webhooks/pod_mutating_webhook.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#437 Update installation docs for v0.4.0
  docs/setup/install.md
Labels: cncf-cla: yes, lgtm, approved, size/S
