Repository kubernetes-sigs/jobset, pull requests merged in 2024-11, with the labels that each got.

#694 Image support multi-arch
  Dockerfile
  Makefile
Labels: kind/feature, cncf-cla: yes, ok-to-test, lgtm, size/XS, approved

#695 Use meta api native condition status
  pkg/controllers/failure_policy.go
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
Labels: cncf-cla: yes, lgtm, kind/cleanup, approved, size/S

#696 Introduce Go std slices and maps lib
  go.mod
  pkg/controllers/jobset_controller.go
  pkg/controllers/success_policy.go
  pkg/util/collections/collections.go
  pkg/util/collections/collections_test.go
  pkg/webhooks/jobset_webhook.go
  test/integration/controller/jobset_controller_test.go
Labels: tide/merge-method-squash, cncf-cla: yes, lgtm, kind/cleanup, size/L, approved

#697 Remove duplicated condition judgement
  pkg/controllers/jobset_controller.go
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#702 Add Coordinator concept
  site/content/en/docs/concepts/_index.md
Labels: cncf-cla: yes, ok-to-test, size/M, lgtm, approved, kind/documentation

#705 Propagate schedulingGates set on PodTemplate when resuming JobSet
  pkg/controllers/jobset_controller.go
  test/e2e/e2e_test.go
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, approved

#706 Automated cherry pick of #705: Propagate schedulingGates set on PodTemplate when resuming
  pkg/controllers/jobset_controller.go
  test/e2e/e2e_test.go
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, approved

#711 Update docs for v0.7.1 (release branch)
  README.md
  site/config.toml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#712 Update docs for release v0.7.1
  README.md
  site/config.toml
Labels: cncf-cla: yes, lgtm, size/XS, approved
