Repository kubernetes-sigs/jobset, pull requests merged in 2024-01, with the labels that each got.

#359 update kind to 0.20.0
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#387 upgrade kubernetes apis to 0.29
  client-go/informers/externalversions/factory.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XL, lgtm, approved

#389 Move exclusive placement annotation to ReplicatedJob template
  api/jobset/v1alpha2/jobset_types.go
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/util/testing/wrappers.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#391 add dependabot groups for k8s packages
  .github/dependabot.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#390 add a message to events
  pkg/controllers/jobset_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved
