Repository kubernetes-sigs/jobset, pull requests merged in 2025-06, with the labels that each got.

#905 remove omitempty annotation for restarts field in JobSet status
  api/jobset/v1alpha2/jobset_types.go
  api/jobset/v1alpha2/openapi_generated.go
  hack/python-sdk/swagger.json
  sdk/python/jobset/models/jobset_v1alpha2_job_set_status.py
Labels: kind/feature, cncf-cla: yes, ok-to-test, lgtm, kind/api-change, approved, size/S

#913 update kind to 0.29.0
  Makefile
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#922 Allow Docker to cache intermediate dependency installation steps
  Dockerfile
  Makefile
Labels: cncf-cla: yes, ok-to-test, lgtm, kind/cleanup, approved, size/S

#916 fix e2e testing list and add a 2025 roadmap
  site/content/en/docs/overview/_index.md
Labels: cncf-cla: yes, lgtm, approved, size/S, kind/documentation
