Repository kubernetes-sigs/jobset, pull requests merged in 2025-09, with the labels that each got.

#992 chore(docs): Changelog for JobSet v0.9.0
  CHANGELOG/CHANGELOG-0.9.md
  CHANGELOG/README.md
Labels: cncf-cla: yes, lgtm, size/L, approved, kind/documentation

#991 add test-infra requirement for release
  .github/ISSUE_TEMPLATE/new-release.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, kind/documentation

#999 use chart version and app version to match kueue tagging
  hack/push-chart.sh
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#1001 refactor helm chart push for DRY
  Makefile
  hack/helm-chart-package.sh
Labels: cncf-cla: yes, lgtm, kind/cleanup, approved, size/S

#1007 add release branch to correct tagging
  Makefile
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#1011 use 1.34 for envtest and update prod page for 1.34
  Makefile
  README.md
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#1022 Filter out terminating leader Pods
  pkg/controllers/pod_controller.go
  pkg/webhooks/pod_admission_webhook.go
  pkg/webhooks/pod_admission_webhook_test.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/L, approved

#1013 chore(release): Create prepare-release-branch script
  .github/ISSUE_TEMPLATE/new-release.md
  Makefile
  hack/helm-chart-package.sh
  site/content/en/docs/overview/_index.md
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/documentation

#1034 Use version without v for helm
  charts/jobset/README.md
  charts/jobset/README.md.gotmpl
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#1027 Update failure policy KEP: distinguish retriable from non retriable Pod failure policies
  keps/262-ConfigurableFailurePolicy/README.md
Labels: kind/feature, cncf-cla: yes, lgtm, size/L, kind/api-change, approved

#1033 Add onJobFailureMessagePatterns to distinguish retriable from non retriable Pod failure policies
  api/jobset/v1alpha2/jobset_types.go
  api/jobset/v1alpha2/openapi_generated.go
  api/jobset/v1alpha2/zz_generated.deepcopy.go
  client-go/applyconfiguration/jobset/v1alpha2/failurepolicyrule.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  hack/python-sdk/swagger.json
  pkg/controllers/failure_policy.go
  pkg/controllers/failure_policy_test.go
  sdk/python/jobset/models/jobset_v1alpha2_failure_policy_rule.py
  sdk/python/test/test_jobset_v1alpha2_failure_policy.py
  sdk/python/test/test_jobset_v1alpha2_failure_policy_rule.py
  sdk/python/test/test_jobset_v1alpha2_job_set.py
  sdk/python/test/test_jobset_v1alpha2_job_set_list.py
  sdk/python/test/test_jobset_v1alpha2_job_set_spec.py
  site/content/en/docs/reference/jobset.v1alpha2.md
  test/integration/controller/jobset_controller_test.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/L, kind/api-change, approved

#1040 Run prepare release script and update changelog
  CHANGELOG/CHANGELOG-0.9.md
  config/components/manager/kustomization.yaml
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#1044 Run prepare release script and update changelog
  CHANGELOG/CHANGELOG-0.10.md
  Makefile
  README.md
  charts/jobset/Chart.yaml
  charts/jobset/README.md
  config/components/manager/kustomization.yaml
  site/hugo.toml
Labels: cncf-cla: yes, size/M, lgtm, kind/cleanup, approved

#1051 update to v0.10.1 in main
  README.md
  charts/jobset/Chart.yaml
  charts/jobset/README.md
  site/hugo.toml
Labels: cncf-cla: yes, lgtm, kind/cleanup, approved, size/S
