Repository kubernetes-sigs/jobset, pull requests merged in 2025-03, with the labels that each got.

#811 Add minimal helm installation instructions
  site/content/en/docs/installation/_index.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#812 Update the helm repo link
  site/content/en/docs/installation/_index.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#821 pin envtest
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#815 fix wrong cmd of output service
  site/content/en/docs/concepts/_index.md
Labels: cncf-cla: yes, ok-to-test, lgtm, kind/cleanup, size/XS, approved, kind/documentation

#819 bug fix: fix depends on validation if there are no replicated jobs
  api/jobset/v1alpha2/jobset_types.go
  charts/jobset/crds/jobset.x-k8s.io_jobsets.yaml
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  pkg/webhooks/jobset_webhook.go
  pkg/webhooks/jobset_webhook_test.go
  test/integration/webhook/jobset_webhook_test.go
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, approved

#823 Add .helmignore file to ignore files when packging the Helm chart
  charts/jobset/.helmignore
Labels: cncf-cla: yes, ok-to-test, size/M, lgtm, kind/cleanup, approved

#822 Add group labels / annotations for replicated jobs grouping
  api/jobset/v1alpha2/jobset_types.go
  api/jobset/v1alpha2/openapi_generated.go
  client-go/applyconfiguration/jobset/v1alpha2/replicatedjob.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  hack/python-sdk/swagger.json
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/util/testing/wrappers.go
  pkg/webhooks/jobset_webhook.go
  pkg/webhooks/jobset_webhook_test.go
  sdk/python/jobset/models/jobset_v1alpha2_replicated_job.py
  sdk/python/test/test_jobset_v1alpha2_job_set.py
  sdk/python/test/test_jobset_v1alpha2_job_set_list.py
  sdk/python/test/test_jobset_v1alpha2_job_set_spec.py
  sdk/python/test/test_jobset_v1alpha2_replicated_job.py
Labels: kind/feature, cncf-cla: yes, ok-to-test, size/XL, lgtm, approved

#833 update controller tools to v0.17.2
  Makefile
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#840 update k8s dependencies to 0.32.3 without dependabot
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, lgtm, kind/cleanup, approved

#842 move subcharts to nested level
  Makefile
  hack/push-chart.sh
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#845 Set readOnlyRootFilesystem explicitly to true
  charts/jobset/values.yaml
  config/components/manager/manager.yaml
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#844 Default to 8443 as metrics port to align service instead of 8080
  api/config/v1alpha1/defaults.go
  charts/jobset/templates/controller/deployment.yaml
  config/default/kustomization.yaml
  config/default/manager_metrics_patch.yaml
  main.go
  pkg/config/config_test.go
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, approved

#841 update to golang 1.24
  Makefile
  go.mod
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#850 add yq to artifacts makefile
  Makefile
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#851 add helm verify step and fix some minor items
  Makefile
  charts/jobset/README.md
  charts/jobset/tests/controller/deployment_test.yaml
Labels: cncf-cla: yes, lgtm, kind/cleanup, approved, size/S

#856 Update main with v0.8.1 changes
  .github/ISSUE_TEMPLATE/new-release.md
  charts/jobset/Chart.yaml
  charts/jobset/README.md
  charts/jobset/README.md.gotmpl
  site/config.toml
Labels: cncf-cla: yes, size/M, lgtm, kind/cleanup, approved

#828 bump envtest
  Makefile
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#852 feat(docs): Create JobSet adopters page
  site/content/en/docs/adopters/_index.md
Labels: cncf-cla: yes, lgtm, approved, size/S, kind/documentation

#859 docs: redirect / to /docs/overview
  site/assets/icons/logo.svg
  site/content/en/_index.html
  site/content/en/docs/overview/_index.md
  site/static/images/jobset_diagram.png
Labels: cncf-cla: yes, lgtm, size/L, approved, kind/documentation
