Repository kubernetes-sigs/jobset, pull requests merged in 2025-01, with the labels that each got.

#744 Bump braces from 3.0.2 to 3.0.3 in /site
  site/package-lock.json
Labels: cncf-cla: yes, lgtm, kind/cleanup, approved, size/S

#738 update k8s to 0.32 apis
  client-go/applyconfiguration/internal/internal.go
  client-go/applyconfiguration/jobset/v1alpha2/failurepolicy.go
  client-go/applyconfiguration/jobset/v1alpha2/failurepolicyrule.go
  client-go/applyconfiguration/jobset/v1alpha2/jobset.go
  client-go/applyconfiguration/jobset/v1alpha2/startuppolicy.go
  client-go/applyconfiguration/jobset/v1alpha2/successpolicy.go
  client-go/clientset/versioned/clientset.go
  client-go/clientset/versioned/typed/jobset/v1alpha2/fake/fake_jobset.go
  client-go/clientset/versioned/typed/jobset/v1alpha2/fake/fake_jobset_client.go
  client-go/clientset/versioned/typed/jobset/v1alpha2/jobset.go
  client-go/clientset/versioned/typed/jobset/v1alpha2/jobset_client.go
  client-go/informers/externalversions/generic.go
  client-go/informers/externalversions/jobset/v1alpha2/jobset.go
  client-go/listers/jobset/v1alpha2/jobset.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XL, lgtm, approved

#737 Propagate job labels and annotations
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/util/testing/wrappers.go
Labels: kind/bug, tide/merge-method-squash, cncf-cla: yes, ok-to-test, size/M, lgtm, approved

#745 disable http/2 for metrics server
  main.go
Labels: cncf-cla: yes, lgtm, kind/cleanup, approved, size/S

#746 Minimize the number of unnecessary logs that get emitted
  pkg/controllers/jobset_controller.go
Labels: tide/merge-method-squash, cncf-cla: yes, ok-to-test, lgtm, approved, size/S

#749 inject namespace in case we want to test against non standard deployment
  hack/e2e-test.sh
  test/e2e/suite_test.go
Labels: kind/feature, cncf-cla: yes, lgtm, approved, size/S

#743 fix security warnings in client go code
  site/static/examples/client-go/go.mod
  site/static/examples/client-go/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved

#751 [Release 0.7]: cherry-pick allow for one to install jobset in a different namespace
  main.go
  pkg/util/cert/cert.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/S

#752 Remove Namespace from the JobSet Config
  api/config/v1alpha1/configuration_types.go
  api/config/v1alpha1/defaults.go
  api/config/v1alpha1/defaults_test.go
  api/config/v1alpha1/zz_generated.deepcopy.go
  pkg/config/config_test.go
  pkg/util/cert/cert.go
Labels: cncf-cla: yes, ok-to-test, lgtm, kind/cleanup, size/L, approved

#755 Turn off internal cert management via config
  main.go
Labels: kind/bug, kind/feature, cncf-cla: yes, ok-to-test, lgtm, approved, size/S

#681 update gen-sdk.sh to generate sdk using docker container
  hack/python-sdk/gen-sdk.sh
Labels: kind/feature, tide/merge-method-squash, cncf-cla: yes, ok-to-test, lgtm, approved, size/S

#756 Use config metrics binding address if flag is not set
  main.go
Labels: kind/bug, cncf-cla: yes, ok-to-test, lgtm, size/XS, approved

#757 [release-0.7]: cherry-pick turn off internal cert management via config
  main.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/S

#758 Self nominate Kevin Hannon for approval rights
  OWNERS
  site/OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved, kind/documentation

#765 copy all files in project rather than piece by piece
  Dockerfile
Labels: cncf-cla: yes, lgtm, kind/cleanup, approved, size/S

#761 update release docs with latest patch release
  README.md
  site/config.toml
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#767 [release-0.7] propose kevin hannon for approval rights (#758)
  OWNERS
  site/OWNERS
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#769 add go mod download to Dockerfile
  Dockerfile
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#770 update python sdk files with latest changes
  .gitignore
  Makefile
  sdk/python/.gitlab-ci.yml
  sdk/python/.openapi-generator/FILES
  sdk/python/.openapi-generator/VERSION
  sdk/python/.travis.yml
  sdk/python/README.md
  sdk/python/docs/JobsetV1alpha2Coordinator.md
  sdk/python/docs/JobsetV1alpha2FailurePolicy.md
  sdk/python/docs/JobsetV1alpha2FailurePolicyRule.md
  sdk/python/docs/JobsetV1alpha2JobSet.md
  sdk/python/docs/JobsetV1alpha2JobSetList.md
  sdk/python/docs/JobsetV1alpha2JobSetSpec.md
  sdk/python/docs/JobsetV1alpha2JobSetStatus.md
  sdk/python/docs/JobsetV1alpha2Network.md
  sdk/python/docs/JobsetV1alpha2ReplicatedJob.md
  sdk/python/docs/JobsetV1alpha2ReplicatedJobStatus.md
  sdk/python/docs/JobsetV1alpha2StartupPolicy.md
  sdk/python/docs/JobsetV1alpha2SuccessPolicy.md
  sdk/python/git_push.sh
  sdk/python/jobset/__init__.py
  sdk/python/jobset/api/__init__.py
  sdk/python/jobset/api_client.py
  sdk/python/jobset/api_response.py
  sdk/python/jobset/configuration.py
  sdk/python/jobset/exceptions.py
  sdk/python/jobset/models/__init__.py
  sdk/python/jobset/models/jobset_v1alpha2_coordinator.py
  sdk/python/jobset/models/jobset_v1alpha2_failure_policy.py
  sdk/python/jobset/models/jobset_v1alpha2_failure_policy_rule.py
  sdk/python/jobset/models/jobset_v1alpha2_job_set.py
  sdk/python/jobset/models/jobset_v1alpha2_job_set_list.py
  sdk/python/jobset/models/jobset_v1alpha2_job_set_spec.py
  sdk/python/jobset/models/jobset_v1alpha2_job_set_status.py
  sdk/python/jobset/models/jobset_v1alpha2_network.py
  sdk/python/jobset/models/jobset_v1alpha2_replicated_job.py
  sdk/python/jobset/models/jobset_v1alpha2_replicated_job_status.py
  sdk/python/jobset/models/jobset_v1alpha2_startup_policy.py
  sdk/python/jobset/models/jobset_v1alpha2_success_policy.py
  sdk/python/jobset/py.typed
  sdk/python/jobset/rest.py
  sdk/python/pyproject.toml
  sdk/python/requirements.txt
  sdk/python/test-requirements.txt
  sdk/python/test/test_jobset_v1alpha2_coordinator.py
  sdk/python/test/test_jobset_v1alpha2_failure_policy.py
  sdk/python/test/test_jobset_v1alpha2_failure_policy_rule.py
  sdk/python/test/test_jobset_v1alpha2_job_set.py
  sdk/python/test/test_jobset_v1alpha2_job_set_list.py
  sdk/python/test/test_jobset_v1alpha2_job_set_spec.py
  sdk/python/test/test_jobset_v1alpha2_job_set_status.py
  sdk/python/test/test_jobset_v1alpha2_network.py
  sdk/python/test/test_jobset_v1alpha2_replicated_job.py
  sdk/python/test/test_jobset_v1alpha2_replicated_job_status.py
  sdk/python/test/test_jobset_v1alpha2_startup_policy.py
  sdk/python/test/test_jobset_v1alpha2_success_policy.py
  sdk/python/tox.ini
Labels: cncf-cla: yes, size/XXL, lgtm, kind/cleanup, approved

#740 KEP-672: Implement the DependsOn API
  Makefile
  api/jobset/v1alpha2/jobset_types.go
  api/jobset/v1alpha2/openapi_generated.go
  api/jobset/v1alpha2/zz_generated.deepcopy.go
  client-go/applyconfiguration/jobset/v1alpha2/dependson.go
  client-go/applyconfiguration/jobset/v1alpha2/replicatedjob.go
  client-go/applyconfiguration/utils.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  hack/python-sdk/swagger.json
  keps/672-serial-job-execution/README.md
  pkg/controllers/depends_on.go
  pkg/controllers/depends_on_test.go
  pkg/controllers/jobset_controller.go
  pkg/controllers/startup_policy.go
  pkg/controllers/startup_policy_test.go
  pkg/util/testing/wrappers.go
  pkg/webhooks/jobset_webhook.go
  pkg/webhooks/jobset_webhook_test.go
  sdk/python/.openapi-generator/FILES
  sdk/python/README.md
  sdk/python/docs/JobsetV1alpha1FailurePolicy.md
  sdk/python/docs/JobsetV1alpha1JobSet.md
  sdk/python/docs/JobsetV1alpha1JobSetList.md
  sdk/python/docs/JobsetV1alpha1JobSetSpec.md
  sdk/python/docs/JobsetV1alpha1JobSetStatus.md
  sdk/python/docs/JobsetV1alpha1Network.md
  sdk/python/docs/JobsetV1alpha1ReplicatedJob.md
  sdk/python/docs/JobsetV1alpha1ReplicatedJobStatus.md
  sdk/python/docs/JobsetV1alpha1SuccessPolicy.md
  sdk/python/docs/JobsetV1alpha2DependsOn.md
  sdk/python/docs/JobsetV1alpha2ReplicatedJob.md
  sdk/python/docs/JobsetV1alpha2TargetReplicatedJobStartup.md
  sdk/python/jobset/__init__.py
  sdk/python/jobset/models/__init__.py
  sdk/python/jobset/models/jobset_v1alpha2_depends_on.py
  sdk/python/jobset/models/jobset_v1alpha2_replicated_job.py
  sdk/python/test/test_jobset_v1alpha2_depends_on.py
  sdk/python/test/test_jobset_v1alpha2_job_set.py
  sdk/python/test/test_jobset_v1alpha2_job_set_list.py
  sdk/python/test/test_jobset_v1alpha2_job_set_spec.py
  sdk/python/test/test_jobset_v1alpha2_replicated_job.py
  site/content/en/docs/tasks/_index.md
  site/static/examples/depends-on/depends-on.yaml
  test/e2e/e2e_test.go
  test/integration/controller/jobset_controller_test.go
  test/integration/webhook/jobset_webhook_test.go
Labels: kind/feature, cncf-cla: yes, ok-to-test, size/XXL, lgtm, kind/api-change, approved
