Repository kubernetes-sigs/jobset, pull requests merged in 2025-02, with the labels that each got.

#775 Set user agent for requests coming from the jobset controller to "jobset"
  main.go
  pkg/util/useragent/useragent.go
  pkg/util/useragent/useragent_test.go
  pkg/version/version.go
Labels: cncf-cla: yes, ok-to-test, lgtm, size/L, approved

#779 Updating the documentation for Pod DNS and underlying headless service.
  site/content/en/docs/concepts/_index.md
Labels: cncf-cla: yes, ok-to-test, lgtm, approved, size/S, kind/documentation

#781 Remove the Configuration API as a CRD
  config/components/crd/bases/jobset.x-k8s.io_configurations.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_configurations.yaml
  config/crd/patches/webhook_in_configurations.yaml
  config/rbac/configuration_editor_role.yaml
  config/rbac/configuration_viewer_role.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved

#780 Set image tag and commit version at build time
  Dockerfile
  Makefile
  main.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#783 Increase memory limit and remove cpu limit for the default deployment
  config/components/manager/manager.yaml
Labels: cncf-cla: yes, ok-to-test, lgtm, size/XS, approved

#782 Add missing external types to apply configurations
  client-go/applyconfiguration/jobset/v1alpha2/replicatedjob.go
  hack/update-codegen.sh
Labels: kind/bug, cncf-cla: yes, lgtm, kind/api-change, approved, size/S

#785 feature: add Helm chart for jobset
  Makefile
  charts/jobset/Chart.yaml
  charts/jobset/README.md
  charts/jobset/README.md.gotmpl
  charts/jobset/crds/jobset.x-k8s.io_jobsets.yaml
  charts/jobset/templates/NOTES.txt
  charts/jobset/templates/_helpers.tpl
  charts/jobset/templates/certmanager/_helpers.tpl
  charts/jobset/templates/certmanager/certificate.yaml
  charts/jobset/templates/certmanager/issuer.yaml
  charts/jobset/templates/controller/_helpers.tpl
  charts/jobset/templates/controller/cluster_role.yaml
  charts/jobset/templates/controller/cluster_role_binding.yaml
  charts/jobset/templates/controller/configmap.yaml
  charts/jobset/templates/controller/deployment.yaml
  charts/jobset/templates/controller/role.yaml
  charts/jobset/templates/controller/role_binding.yaml
  charts/jobset/templates/controller/service_account.yaml
  charts/jobset/templates/prometheus/_helpers.tpl
  charts/jobset/templates/prometheus/service.yaml
  charts/jobset/templates/prometheus/service_monitor.yaml
  charts/jobset/templates/webhook/_helpers.tpl
  charts/jobset/templates/webhook/mutating_webhook_configuration.yaml
  charts/jobset/templates/webhook/secret.yaml
  charts/jobset/templates/webhook/service.yaml
  charts/jobset/templates/webhook/validating_webhook_configuration.yaml
  charts/jobset/tests/certmanager/certificate_test.yaml
  charts/jobset/tests/certmanager/issuer_test.yaml
  charts/jobset/tests/controller/deployment_test.yaml
  charts/jobset/tests/prometheus/service_monitor_test.yaml
  charts/jobset/tests/prometheus/service_test.yaml
  charts/jobset/tests/webhook/secret_test.yaml
  charts/jobset/values.yaml
Labels: kind/feature, cncf-cla: yes, ok-to-test, size/XXL, lgtm, approved

#789 helm: disable Promethues metrics exporting by default
  charts/jobset/README.md
  charts/jobset/templates/prometheus/service_monitor.yaml
  charts/jobset/tests/prometheus/service_monitor_test.yaml
  charts/jobset/tests/prometheus/service_test.yaml
  charts/jobset/values.yaml
Labels: kind/feature, cncf-cla: yes, ok-to-test, lgtm, approved, size/S

#792 add make file targets for helm
  Makefile
  charts/jobset/values.yaml
  cloudbuild.yaml
  config/components/manager/kustomization.yaml
  hack/e2e-test.sh
  hack/push-chart.sh
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/L, approved

#798 Fix helm chart push but disable it from cloud build for testing
  Makefile
  charts/jobset/values.yaml
  cloudbuild.yaml
  hack/push-chart.sh
Labels: cncf-cla: yes, lgtm, kind/cleanup, approved, size/S

#799 enable helm chart push for cloudbuild for postsubmit
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#802 update docs for release 0.8
  README.md
  site/config.toml
Labels: cncf-cla: yes, lgtm, size/XS, approved, kind/documentation

#804 update reference data
  site/content/en/docs/reference/jobset.v1alpha2.md
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/documentation

#806 Bump OpenAPI Generator CLI to v7.11.0
  hack/python-sdk/gen-sdk.sh
  sdk/python/.openapi-generator/VERSION
  sdk/python/README.md
Labels: kind/bug, cncf-cla: yes, ok-to-test, lgtm, size/XS, approved

#807 Automated cherry pick of #803: fix repository bug
  Makefile
  charts/jobset/README.md
  charts/jobset/templates/_helpers.tpl
  charts/jobset/templates/controller/deployment.yaml
  charts/jobset/values.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S
