Repository kubernetes-sigs/jobset, pull requests merged in 2025-04, with the labels that each got.

#864 bump builder golang image to 1.24
  Dockerfile
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#870 update helm CRD to include ReplicatedJob groupName
  charts/jobset/crds/jobset.x-k8s.io_jobsets.yaml
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved

#869 mention field paths and values of invalid fields
  pkg/webhooks/jobset_webhook.go
Labels: kind/bug, cncf-cla: yes, lgtm, kind/cleanup, approved, size/S

#871 Fix typo in JobSetStatus.TeminalState docs.
  api/jobset/v1alpha2/jobset_types.go
  api/jobset/v1alpha2/openapi_generated.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  sdk/python/jobset/models/jobset_v1alpha2_job_set_status.py
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#862 Add a JobSet label for Pods with the UID of the JobSet.
  api/jobset/v1alpha2/jobset_types.go
  pkg/controllers/jobset_controller.go
  pkg/controllers/jobset_controller_test.go
  pkg/controllers/pod_controller_test.go
  site/content/en/docs/concepts/_index.md
Labels: kind/feature, cncf-cla: yes, ok-to-test, lgtm, approved, size/S

#883 chore: Replace completionModePtr with ptr.To()
  pkg/webhooks/jobset_webhook.go
  pkg/webhooks/jobset_webhook_test.go
Labels: cncf-cla: yes, size/M, lgtm, kind/cleanup, approved

#881 Simplify replicatedJob name validations
  pkg/webhooks/jobset_webhook.go
Labels: cncf-cla: yes, size/M, lgtm, kind/cleanup, approved

#882 chore: Upgrade the default k8s versions for E2E and integration tests cluster
  Makefile
  test/integration/controller/jobset_controller_test.go
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/L, approved

#877 docs: support multiple items in DependsOn API
  keps/672-serial-job-execution/README.md
Labels: cncf-cla: yes, ok-to-test, lgtm, size/L, approved, kind/documentation

#890 update toc for kep 672
  keps/672-serial-job-execution/README.md
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#889 separate metrics one label [<name>/<namespace>] to two label [<name>, <namespace>]
  pkg/controllers/failure_policy.go
  pkg/controllers/jobset_controller.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  site/content/en/docs/reference/metrics.md
Labels: cncf-cla: yes, size/M, lgtm, kind/cleanup, approved

#892 Update kustomize version to v5.2.1
  Makefile
  config/components/crd/kustomization.yaml
  config/components/manager/controller_manager_config.yaml
  config/default/kustomization.yaml
  test/e2e/config/kustomization.yaml
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/L, approved

#895 feat: add example for multiple DependsOn items.
  site/content/en/docs/tasks/_index.md
  site/static/examples/depends-on/multiple-depends-on.yaml
Labels: kind/feature, cncf-cla: yes, ok-to-test, size/M, lgtm, approved

#894 update kubernetes to 0.33
  client-go/clientset/versioned/fake/clientset_generated.go
  client-go/clientset/versioned/typed/jobset/v1alpha2/jobset_client.go
  client-go/informers/externalversions/jobset/v1alpha2/jobset.go
  config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml
  go.mod
  go.sum
  hack/python-sdk/swagger.json
  sdk/python/jobset/models/io_k8s_api_batch_v1_job_spec.py
  sdk/python/jobset/models/io_k8s_api_batch_v1_pod_failure_policy_rule.py
  sdk/python/jobset/models/io_k8s_api_core_v1_env_from_source.py
  sdk/python/jobset/models/io_k8s_api_core_v1_lifecycle.py
  sdk/python/jobset/models/io_k8s_api_core_v1_pod_affinity_term.py
  sdk/python/jobset/models/io_k8s_api_core_v1_pod_spec.py
  sdk/python/jobset/models/io_k8s_api_core_v1_topology_spread_constraint.py
  sdk/python/test/test_io_k8s_api_batch_v1_job_spec.py
  sdk/python/test/test_io_k8s_api_core_v1_container.py
  sdk/python/test/test_io_k8s_api_core_v1_ephemeral_container.py
  sdk/python/test/test_io_k8s_api_core_v1_lifecycle.py
  sdk/python/test/test_io_k8s_api_core_v1_pod_spec.py
  sdk/python/test/test_io_k8s_api_core_v1_pod_template_spec.py
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/L, approved
