Repository kubernetes-sigs/jobset, pull requests merged in 2025-05, with the labels that each got.

#897 update golangci to v2
  .golangci.yaml
  Makefile
  hack/swagger/main.go
  pkg/controllers/jobset_controller.go
  pkg/controllers/success_policy.go
  pkg/controllers/ttl_after_finished_test.go
  pkg/util/testing/wrappers.go
  pkg/webhooks/jobset_webhook.go
Labels: cncf-cla: yes, size/M, lgtm, kind/cleanup, approved

#901 Use correct links to examples
  site/content/en/docs/overview/_index.md
  site/content/en/docs/troubleshooting/_index.md
Labels: cncf-cla: yes, ok-to-test, lgtm, approved, size/S, kind/documentation

#903 Fix broken helm link to correct one
  site/content/en/docs/installation/_index.md
Labels: cncf-cla: yes, ok-to-test, lgtm, size/XS, approved, kind/documentation
