Repository kubernetes-sigs/jobset, pull requests merged in 2025-07, with the labels that each got.

#932 Remove workaround for code-generator
  hack/update-codegen.sh
Labels: cncf-cla: yes, lgtm, kind/cleanup, size/XS, approved

#931 fix: handle nil Completions in coordinator validation
  pkg/webhooks/jobset_webhook.go
  pkg/webhooks/jobset_webhook_test.go
Labels: kind/bug, cncf-cla: yes, ok-to-test, size/M, lgtm, approved

#935 [release-0.8] fix: handle nil Completions in coordinator validation
  pkg/webhooks/jobset_webhook.go
  pkg/webhooks/jobset_webhook_test.go
Labels: cncf-cla: yes, ok-to-test, size/M, lgtm, approved

#933 Updated Makefile for s390x support
  Makefile
Labels: kind/feature, cncf-cla: yes, ok-to-test, lgtm, size/XS, approved

#925 Update failure policy KEP with proposed RecreateJob behavior
  keps/262-ConfigurableFailurePolicy/README.md
Labels: cncf-cla: yes, ok-to-test, lgtm, size/L, kind/api-change, approved, kind/documentation

#938 cleanup: e2e tests: Don't sleep in trainer jobs
  keps/262-ConfigurableFailurePolicy/README.md
  test/e2e/e2e_test.go
  test/e2e/suite_test.go
Labels: cncf-cla: yes, ok-to-test, lgtm, kind/cleanup, approved, size/S

#949 e2e tests: Improve a flaky DependsOn test
  test/e2e/e2e_test.go
Labels: kind/flake, cncf-cla: yes, ok-to-test, lgtm, kind/cleanup, size/XS, approved

#955 self nominate andreyvelich for approval rights
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved, kind/documentation

#954 Adding GiuseppeTT as a reviewer for jobset
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved, kind/documentation

#951 Rework "Tasks" docs site section and add detailed failure policy examples
  site/content/en/docs/overview/_index.md
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/failure_policy.md
  site/content/en/docs/tasks/simple_examples.md
  site/content/en/docs/tasks/workload_examples.md
Labels: cncf-cla: yes, ok-to-test, lgtm, size/L, approved, kind/documentation

#960 test/e2e: Test foreground cascading deletion
  test/e2e/e2e_test.go
Labels: kind/feature, cncf-cla: yes, ok-to-test, lgtm, approved, size/S

#964 Add dev environment setup guidelines to docs site
  CONTRIBUTING.md
  site/content/en/docs/contribution_guidelines/_index.md
  site/content/en/docs/contribution_guidelines/development.md
Labels: cncf-cla: yes, ok-to-test, size/M, lgtm, approved, kind/documentation
